### ISSUE TITLE
☂️   0.1 Release Tasks

### ISSUE THREAD

**Issue by jamiebuilds** [rome/tools#1570]
- [x] Turn off CSS support temporarily (won't be ready in time)
- [x] #1360 "Add support for fixes in ESLint integration"
- [x] #1388 "Remove hardcoded path from ESLint integration"
- [x] Add ESLint interop option (go through ESLint flags to see which ones we need to support)
- [ ] Test ESLint integration against popular ESLint plugins
- [x] Test ESLint integration against projects already using ESLint
- [x] Basic Prettier support (if you are using a `.prettierrc` it should just work)
- [x] Disable our formatter by default?
- [x] Stabilize LSP server #1608 
- [x] Improve LSP spec compliance
- [x] Fix/improve LSP code action support
- [ ] Improved Contributing Docs
- [ ] Discuss: One config format, in one place https://github.com/rome/tools/issues/1596
- [x] Disable dependency check during `rome check` command https://github.com/rome/tools/issues/1607
- [ ] Display auto-fix code actions as quick fixes in VS Code https://github.com/rome/tools/issues/1619
- [ ] Update governance structure https://github.com/rome/tools/issues/1324#issue-801438375

**Comment by ematipico** [comment]
Working on the basic prettier support

**Comment by yassere** [comment]
We should also stabilize the LSP Server and improve its spec compliance. I'm working on that now.

**Comment by jamiebuilds** [comment]
@yassere You mind adding tasks that you need to work on to this issue?

**Comment by ematipico** [comment]
Currently working on the eslint interop.

**Comment by jamiebuilds** [comment]
@ematipico @yassere Could you add some details about removing dependency checking, and simplifying the LSP and `rome check` commands?

**Comment by sebmck** [comment]
Opened #1607

**Comment by ematipico** [comment]
The integrations are ready! Now that we decided to turn off dependency check and manifest, maybe we might able to add to the CI the integrations. 

Before it wasn't an option.

**Comment by yassere** [comment]
There's more we can do to improve LSP spec compliance and code action support, but I think they're good enough now to no longer be blockers for this release.

**Comment by jer3m01** [comment]
We should also add a task to update GOVERNANCE.md.

**Comment by ematipico** [comment]
@sebmck @jamiebuilds the governance one should assigned to one of you.

**Comment by jamiebuilds** [comment]
Hi! Thank you for opening this issue

We recently made the decision to [migrate the Rome codebase to Rust](https://rome.tools/blog/2021/09/21/rome-will-be-rewritten-in-rust) and making some significant changes to its architecture. We've also decided not to release the previous version written in TypeScript.

We're going through and closing pull requests and issues that were specific to the TypeScript codebase, including this one. Thank you for taking the time to open it.

Thanks again!
