### ISSUE TITLE
☂️ Use fixed slots for children

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#1724]
### Description

> RSLint and rust-analyzer only store nodes or tokens if they've been present in the source file. Let's take the following example of a `for` statement that only has a condition but misses the `init` and `update` nodes. 
> 
> ```jsx
> for (;i < 10;) {
> }
> ```
> 
> RSLint generates the following CST (ignoring trivia):
> 
> ```yaml
> script:
>   - for-stmt:
>     - for-keyword
>     - l-paren    #// <-- No ForInit after the l-paren
>     - semicolon  
>     - for-test:
>       - binary-expression:
>         - name-ref:
>           - ident(test)
>         - l-angle 
>         - literal
>           - number(10)
>     - semicolon 
>     - r-paren
>     - block
> ```
> 
> The downside of not storing missing (even optional) nodes is that accessing a particular field requires iterating over the children of a node to find its position. For example, the `for-test` is the 4th element if the for-loop has no `for-init` but is the 5th element otherwise. 
> 
> The CST can guarantee fixed positions of its children if missing optional or mandatory children are marked as missing inside its children collection. There are multiple ways to do so, some options are:
> 
> - Storing `None` for missing children
> - Using a fake missing node/token
> - Creating the missing nodes and tokens and flag them as "missing"
> - Use an additional bitmask to encode which nodes are present or missing
> 
> ```yaml
> script:
>   - for-stmt:
>     - for-keyword
>     - l-paren
>     - None # <<<
>     - semicolon
>     - for-test:
>       - binary-expression:
>         - name-ref:
>           - ident(test)
>         - l-angle 
>         - literal:
>           - number(10)
>     - semicolon 
>     - None # <<<
>     - r-paren
>     - block
> ```
> 
> Storing missing elements increases memory consumption because the data structure must encode the information whatever an element is present or missing. We explored different solutions, including bitflags, to mark present and missing elements to keep the overhead to a minimum.

Part of #1718 

See #1721 for discussion around the implementation

- [x] Support empty slots in rowan.  #1761
- [x] Change the parser to inform the `TreeSink` about missing children #1763
- [ ] Change the parser to emit the `missing` children. Probably requires going through the parsing of every node. #1762 
- [x] Create the `SyntaxKind::List` that represents a sequence of children (for example, the statements in a block statement OR the array elements in an array) #1728
- [x] Change the parser to create a `List` node whenever the grammar contains a `T*` or `(T)*` production. Change the codegen for many-field accessors to search for the `List` node and retrieve its children. (see discussion for more details. I don't think it's necessary to implement the `AstList` in this issue but we certainly can). #1728
- [x] Split `UpdateExpression` into `PreUpdateExpression` and `PostUpdateExpression` #1753
- [x] Remove missing/trivia work around in list implementations.

**Comment by MichaReiser** [comment]
I would currently recommend the following design for missing children. It isn’t memory optimized but we can do this later. Missing elements may also be less of an issue if dialects use their own node types to 

- Rename GreenChild to Slot and add a missing variant. Update iterators to skip missing. Change the constructor to accept a Vec<Option<NodeOrToken>>
- Add a missing method to the parser that emits a missing event (morn also to marker that then throws away the started node and replaces it with a missing)
- Add a missing method to the tree builder. 
- handle the missing events in the tree sink
- Add methods to green node and syntax node to get a specific child
