### ISSUE TITLE
Weekly goals - week 44

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#1737]
## Highlevel Goals

* Finish the work around the rowan data structure changes needed for attaching trivia to tokens and using fixed slots for children.
* Decision on lint-transformation API

## Work

- [ ] Publish a design proposal for CST based Lint transformation, agree on a proposal and communicate the decision
- [ ] Attach leading/trailing trivia to tokens #1720 
- [ ] Extend the AST codegen to support the features required by the new JS grammar #1725 
- [ ] Store children in fixed slots #1721 
- [ ] Explore new GitHub features for issue management
- [ ] Explore deployment options and features for crates
- [ ] Align crate licences 
- [ ] Use `rome_` naming convention for all our crates.  @mrkldshv

**Comment by MichaReiser** [comment]
@mrkldshv are you still interested in working on the crate renaming? We've now agreed to go for `rome_` for now. Please don't feel pressured to do work on it before the end of this week.

**Comment by mrkldshv** [comment]
@MichaReiser yeah, I'd like to work on renaming.
