### ISSUE TITLE
☂️ Lexer Improvements 

### ISSUE THREAD

**Issue by xunilrj** [rome/tools#1901]
### Description

We can improve the parser performance by making some improvements on the lexer. First when parsing we need to peeking into ```WHITESPACE``` and ```COMMENT` texts to find newlines. We can avoid this having specific tokens.

With these specific tokens, and the lexer knowing that we had a newline, we can completely remove ```tokens_after_linebreaks```. The lexer will know when a non-trivia token is after a newline. We can attach this info in the ```Token``` struct and completely avoid creating and searching this ```HashSet```.

We can also improve the lexer by already calculating the token offset and remove ```token_offset_pair```. Avoiding a whole iteration when creating the ```Parser```.

The lexer is also returning ```LexerReturn``` or for that matter ```Option<Diagnostics>``` on the stack. Although the super vast majority of the lexing never return any diagnostic, this struct is huge and generate a huge cost by copying data. We can avoid this.

The previous implementation of trivia was focused on optimizing for just one trivia. This change breaks this because we split new lines from whitespace. We may need to refactor this part.  

# Tasks

- [ ] Improve "xtask coverage-libs"
    - [x] Run https://github.com/bheisler/criterion.rs for best results
    - [ ] Flag to display diagnostics
    - [ ] Option to try multiple allocators
- [x] Make https://github.com/matklad/drop_bomb configurable (default only on Debug)
    - [x] ```drop_bomb``` already exclude itself on release builds. We just have to use ```DebugDropBomb```.
- [x] Implement new NEWLINE and MULTILINE_COMMENT token kinds
- [x] Remove token_offset_pair and tokens_after_linebreaks
    - [x] ```next_non_trivia``` ```dir``` as an enum
    - [x] ```raw_lookahead_nth``` must return the last token if it goes out of bounds 
- [x] Improve performance of the lexer, decreasing size of LexerReturn
- [ ] Improve trivia
    - [x] ```NewLine``` and multi line comments on the trivia API
    - [x] Allocate only when necessary inside ```get_trivia```
    - [ ] ```GreenTokenTrivia``` is optimized for zero/one trivia. Does this still make sense?

# NEWLINE Token

Today to know with a WHITESPACE token has a newline, we iterate the token when parsing. We can do better by allowing the lexer to create specific tokens with newline. With this we know that WHITESPACE never has newlines.

Before
```rust
assert_lex! {
	"\n ",
	WHITESPACE:2
}
```

After
```rust
assert_lex! {
	"\n ",
	NEWLINE:1
	WHITESPACE:1
}
```

Or with ```\r\n```

Before 
```rust
assert_lex! {
	" \r\n",
	WHITESPACE:1
	WHITESPACE:2
}
```

After
```rust
assert_lex! {
	" \r\n",
	WHITESPACE:1
	NEWLINE:2
}
```

Today, when we find multiple lines we merge them together in one ```WHITESPACE``` token. Now we are splitting them in multiple ```NEWLINE``` tokens, for example:

```rust

#[test]
fn all_whitespace() {
	...
	assert_lex! {
		"\n\n",
		NEWLINE:1
		NEWLINE:1
	}
        ...
}
```

# MULTILINE_COMMENT Token

We need this token because test262 has one test (https://github.com/tc39/test262/blob/master/test/language/comments/multi-line-asi-carriage-return.js) that basically treats comments ```\**\``` differently when they have a new line.

It states 

> A multi-line comment containing a carriage return should be considered a  LineTerminator

Which means that 

```js
''/*
*/''
```

is different from

```js
''/**/''
```

To avoid having to search a new line inside COMMENT token when parsing, like we are doing today; the lexer will categorize the token whilst it is lexing the code. If some luck, we will be improving performance and making things more clear.

# LexerReturn

```LexeeReturn``` is huge! Doing a ```-Zprint-type-sizes``` we find that Diagnostic alone is 192 bytes.

```
> cargo +nightly rustc -- -Zprint-type-sizes
...
print-type-size type: `rslint_errors::Diagnostic`: 192 bytes, alignment: 8 bytes
print-type-size     field `.file_id`: 8 bytes
print-type-size     field `.code`: 24 bytes
print-type-size     field `.title`: 24 bytes
print-type-size     field `.primary`: 56 bytes
print-type-size     field `.children`: 24 bytes
print-type-size     field `.suggestions`: 24 bytes
print-type-size     field `.footers`: 24 bytes
print-type-size     field `.severity`: 1 bytes
print-type-size     field `.tag`: 1 bytes
print-type-size     end padding: 6 bytes
...
```

Given that ```LexerReturn``` is returned by value in multiple functions, we find the compiler having to copy everything multiple times, for example.

```
>  cargo asm "rslint_parser::parse::tokenize" --rust
...
mov     r13, qword, ptr, [rip, +, memcpy@GOTPCREL]
jmp     .LBB378_2
...
.LBB378_2:
lea     rdi, [rsp, +, 224]
lea     rsi, [rsp, +, 64]
call    qword, ptr, [rip, +, _ZN78_$LT$rslint_lexer..Lexer$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4next17hde555c7f27552293E@GOTPCREL]
movzx   eax, word, ptr, [rsp, +, 232]
cmp     eax, 393
je      .LBB378_4
mov     ebx, dword, ptr, [rsp, +, 232]
mov     rbp, qword, ptr, [rsp, +, 224]
mov     edx, 196
lea     rdi, [rsp, +, 624]
mov     rsi, r12
call    r13
...
```

Relevant here is

```
mov     r13, qword, ptr, [rip, +, memcpy@GOTPCREL]
mov     edx, 196
call    r13
```

```jquery.min``` for example has 41,812 tokens. So just in this function we are coping 8,195,152 bytes, or 8MB. Given that ```LexerReturn``` is moved through two or three function calls, I would not be surprise to see that we are copying at least three times this value.

And to make matters worst, the very next line we throw away this ```Diagnostic``` on 99.99% of the time.

Running Valgrind we see that we spend 7% of the time parsing ```jquery.min``` memcpying stuff. To improve on that, I will box all ```Diagnostic```, hoping that the alloc cost in the end will be much smaller than copying stuff.

```
> valgrind --tool=callgrind --dump-instr=yes --simulate-cache=yes --collect-jumps=yes target/release/xtask coverage-libs --filter=jquery --criterion=false
> kcachegrind
```

![image](https://user-images.githubusercontent.com/83425/148818096-fd636e1c-235e-43fd-9940-b404165888e8.png)

We are not alone:
```https://github.com/rust-lang/rust/issues/64301```
```
I'm going to modify this issue to be about all types that cause many calls to memcpy. These types are all > 128 bytes in size.
```

One way to check is using: https://github.com/jrmuizel/memcpy-find

```
> RUSTFLAGS='-g --emit=llvm-ir' cargo build --release
> 
```

For me this does not work. Not with llvm-13 nor llvm-12, so I went bruteforce.

```
> cat target/release/deps/rslint_lexer-10b324ec6226da3e.ll|grep memcpy|wc -l
3184
```

# Performance Comparison with Chrome

It is very hard to get comparable numbers, but this is how long Chrome/Brave is taking with jquery:

![image](https://user-images.githubusercontent.com/83425/148114202-f7372ce3-d25a-4f65-a1c6-54062f9b17b6.png)

# PRs

#1892
#1902
#1918
#1924
#1928
#1931
#1933

**Comment by xunilrj** [comment]
I am closing this issue because we are not going to work on trivia at the moment.
