### ISSUE TITLE
☂️ Remaining Parsing Errors from Test262

### ISSUE THREAD

**Issue by Boshen** [rome/tools#1909]
### Description

This is the umbrella issue for the remaining 2000+ failed test262 parsing tests.

We aim to pass all tests, please create a separate issue and link them here if you wish to tackle some the of errors.

---
The entire test262 diagnostics can be found in this [gist](https://gist.github.com/Boshen/647c7d85b185fab78ea7bfb49a718293).

All the common features and their respective directories are linked below, you can search the directory names in the [gist](https://gist.github.com/Boshen/647c7d85b185fab78ea7bfb49a718293) for their diagnostics.

---
## Language Features

- [ ] [Regex](https://github.com/tc39/test262/tree/main/test/built-ins/RegExp)
  * `built-ins/RegExp/property-escapes/*`
  * https://github.com/rome/tools/pull/1927
- [ ] [Template Literal](https://github.com/tc39/test262/tree/main/test/language/expressions/template-literal)
- [x] [Top Level Await](https://github.com/tc39/test262/tree/main/src/top-level-await) #1936 
- [ ] [Export Assertion](https://github.com/tc39/test262/tree/main/test/language/module-code) `import-assertion-*.js`
- [x] [Dynamic Import Assertion](https://github.com/tc39/test262/blob/main/test/language/expressions/dynamic-import) 
  * https://github.com/rome/tools/pull/1923
- [x] [Export](https://github.com/tc39/test262/tree/main/test/language/module-code) `*-export-*.js`
  * https://github.com/rome/tools/pull/1915
- [x] [Unicode](https://github.com/tc39/test262/tree/main/test/language/identifiers) `*-unicode-*.js`
  * https://github.com/rome/tools/pull/1910
- [x] [For Await Of](https://github.com/tc39/test262/tree/main/test/language/statements/for-await-of) `async-*.js`
- [ ] [Arrow Function Destructuring](https://github.com/tc39/test262/tree/main/test/language/expressions/arrow-function/dstr)
- ... more cases

## Negative Tests
These are mostly case by case errors, you can search for `Expected this test to fail, but instead it passed without errors.`
- [ ] [Block Scope Redeclaration](https://github.com/tc39/test262/tree/main/test/language/statements/switch/syntax/redeclaration) @ematipico #1929 
- [ ] Early Errors `/early-error/`
- [x] https://github.com/rome/tools/pull/1922
- [x] numbers with leading zero https://github.com/rome/tools/pull/1961
- ... more cases

**Comment by MichaReiser** [comment]
Thanks for categorizing all these errors. 

I'm currently working on Export. 

We may also want to consider not implementing block scope re-declaration checks inside of the parser because it may be expensive to keep all these hash maps, especially with the way our parser state is modelled today. This also seems what babel is doing, for example, 

```js
{
  let a;
  let a;
}
```

this doesn't raise any parse errors in babel or shift.

**Comment by NicholasLYang** [comment]
Should we also ignore private field re-declaration checks then? Something like:
```
class Foo {
 #bar;
 #bar;
}
```

**Comment by xunilrj** [comment]
If https://github.com/rome/tools/pull/1915 is merged we need to fix these 5 tests:

- [ ] Valid unicode escape sequences on identifiers

```
xtask/src/coverage/test262/test\language\module-code\early-dup-assert-key-export.js
xtask/src/coverage/test262/test\language\module-code\early-export-ill-formed-string.js
xtask/src/coverage/test262/test\language\module-code\export-expname-from-as-unpaired-surrogate.js
xtask/src/coverage/test262/test\language\module-code\export-expname-from-unpaired-surrogate.js
xtask/src/coverage/test262/test\language\module-code\export-expname-unpaired-surrogate.js
```

**Comment by MichaReiser** [comment]
I'm currently looking into top-level await, more generally, the way we track where contextual keywords are valid.

**Comment by ematipico** [comment]
I'll work on multiple binding declaration errors, example:

```js
let a;
let a;
```

**Comment by MichaReiser** [comment]
I'll look into disallowing declarations as the body of some statements (for, while, etc.)

**Comment by MichaReiser** [comment]
I'm looking into `static` class initializers.

**Comment by Boshen** [comment]
We are now down to 1736 failures. 🎉 

I have updated the [gist](https://gist.githubusercontent.com/Boshen/647c7d85b185fab78ea7bfb49a718293/raw/50b2ce864ee275c0df3ee4b7b009a9a9a95d4907/xtask%2520coverage%2520output) to include failed source codes.

**Comment by MichaReiser** [comment]
I'm trying to get my head around how labelled statements work.

**Comment by MichaReiser** [comment]
I'll go and look into the `RegExp` parsing. I plan to have a small lexer for RegExp tokens that then parse into a real regular expression AST. 

We probably want to extract this logic into its own parser & lexer at some point in the future but we don't have the infrastructure for that just now which is why I plan to build it inside the JS infra.

**Comment by MichaReiser** [comment]
> I'll go and look into the `RegExp` parsing. I plan to have a small lexer for RegExp tokens that then parse into a real regular expression AST.
> 
> We probably want to extract this logic into its own parser & lexer at some point in the future but we don't have the infrastructure for that just now which is why I plan to build it inside the JS infra.

I'll actually first look into some issues where the parser incorrectly throws an error. Seems more important and the RegEx stuff is certainly a bigger one. 

The first issue I look into now is that we need to allow `in` in `for` heads if the expression is inside a parenthesized expression. I plan to change the way we track the `include_in`, `allow_obj_expr`, and `in_conditional_expr` and hopefully be able to remove them from `ParserState` (and instead pass them explicitly inside of expr).

**Comment by MichaReiser** [comment]
There's one last remaining `incorrectly threw` error related to template literals. I'll look into that to see if I can figure out what must be changed in the lexer.

**Comment by Boshen** [comment]
~1100 errors left!, summary of what's remaining so far:

### The last panic `language/expressions/less-than/S11.8.1_A2.2_T1.js`
```rust
//CHECK#5
if (1 < {toString: function() {return 2}} !== true) {
  throw new Test262Error('#5: 1 < {toString: function() {return 2}} === true. Actual: ' + (1 < {toString: function() {return 2}}));
}
```
panicking in function `ts_property_or_method_sig`

### The last positive test `language/expressions/tagged-template/invalid-escape-sequences.js`
Invalid unicode escape sequence in tagged template literals are allowed (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates_and_escape_sequences under ES2018 revision of illegal escape sequences
), e.g. ```latex`\unicode` ```

### Regex
All negative cases, with these 3 meta feature flags:
* regexp-unicode-property-escapes
* regexp-v-flag
* regexp-named-groups

---

Comment from @MichaReiser 
> We’re also shifting our focus at the moment on parsing all valid js programs but don’t aim to have a parser that reports all semantic errors.

**Comment by MichaReiser** [comment]
> The last positive test language/expressions/tagged-template/invalid-escape-sequences.js

Fixed in #1985
