### ISSUE TITLE
☂️ TypeScript Parsing

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#1966]
### Description

Umbrella task to track the work to get TypeScript parsing in a decent state. 

## Verification

* [x] Run TypeScript's baseline [tests](https://github.com/microsoft/TypeScript/tree/main/tests/baselines/reference) locally
* [x] #2010
* [x] #2022
* [x] Add support for `TypeScript` inline-parser tests: Maybe `test_ts` and `test_err_ts`? See https://github.com/rome/tools/pull/2039

### Types

* [x] #1994

See [type extensions]https://gray-sea-07a57a41e.azurestaticapps.net/#type-grammar)

### Expressions 

See [expression extensions](https://gray-sea-07a57a41e.azurestaticapps.net/#expressions)

* [x] Call-Signatures: Parameter and return-type annotations for methods, getters, setters, arrow functions, and functions #2027
* [x] Non-null-assertion for member expressions #2027
* [x] tagged template literal type arguments #2027
* [x] `<Type> UnaryExpr` cast operator #2027
* [x] `as` cast operator #2027

### Statements

* [x] Interfaces #2058
* [x] Type alias
* [x] #1999
* [x] Variable declarations: type annotations #2050
* [x] Bindings null-assertion operator (may be annoying because the optionality of the type annotation changes when the `!` is present) #2050
* [x] #2090

See [statement extensions](https://gray-sea-07a57a41e.azurestaticapps.net/#statements)

### Functions

* [x] #2046
* [x] Function-declarations without body (should be a different AST node type) #2058

### Classes

* [x] #2059
* [x] `abstract` members (different member node than regular members) #2059
* [x] Type arguments
* [x] implements clause #2058 
* [x] accessibility modifiers
* [x] properties: 
  * [x] `?`, `!`, #2050
  * [x] `readonly` modifiers, and type annotation 
* [x] Index member
* [x] method `?` modifier

See [class extensions](https://gray-sea-07a57a41e.azurestaticapps.net/#classes)

### Scripts / Modules

* [x] #2091
* [x] #2106

### Conformance

#2113

### Non-Goals

* TypeScript declaration files (Ambient script/modules)
* `declare` syntax 
* `decorators`. 

## TODOs

- [ ] Identify syntax that isn't part of the TypeScript spec but supported by TypeScript 4.5

**Comment by Boshen** [comment]
We may need to reconsider about parsing decorators, as the current ecosystem depends heavily on  it. To name a few: angular.js, react redux, nest.js (the backend framework, not next.js)

**Comment by MichaReiser** [comment]
> We may need to reconsider about parsing decorators, as the current ecosystem depends heavily on it. To name a few: angular.js, react redux, nest.js (the backend framework, not next.js)

This is an excellent point. What's outlined here is the goal for an initial TypeScript parser. It doesn't mean that we don't plan to support decorators in the near future, just not from the beginning. Also, JSX/TSX isn't on the list. So its use may be limited at the beginning to library authors that write their whole library in TS.

**Comment by ematipico** [comment]
Rome's scope is to aim for support standard syntax (Stange 3 and Stange 4). 

Experimental syntax is out of the scope of the main Rome package, this doesn't exclude the fact that experimental syntax can be supported via plugins. 

There was a discussion before about decorators and this was the answer: https://github.com/rome/tools/issues/1021#issuecomment-674459163

Essentially, that's a feature that is not settle yet and they are still discussing their implementation (in the meantime it actually changed, so TS supports only the old version).

**Comment by xunilrj** [comment]
One can now see our TS coverage doing:

```
> git submodule init; git submodule update;
Submodule path 'xtask/src/coverage/Typescript': checked out '6c8c829148b42dbc37704c1841f8d6eb6445ac6b'
> cargo run -p xtask --release -- coverage --language=ts
```

**Comment by MichaReiser** [comment]
We may have to reconsider excluding the `declare` syntax. The problem is that many typescript tests make use of the syntax. Not supporting (or at least, skipping over) `declare` statement has the result that all these tests fail.

**Comment by MichaReiser** [comment]
Complete, besides a few conformance issues that we'll track as separate issues
