### ISSUE TITLE
📎 TypeScript: Expression Parsing

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2027]
### Description

See [expression extensions](https://gray-sea-07a57a41e.azurestaticapps.net/#expressions)

* [x] type arguments #2032 
* [x] Function Expression / Declaration (type parameters, parameter). Also implement for methods
* [x] Non-null-assertion for member expressions #2037 
* [x] `<Type> UnaryExpr` cast operator #2033
* [x] `as` cast operator #2033
