### ISSUE TITLE
☂️ Formatting Improvements

### ISSUE THREAD

**Issue by leops** [rome/tools#2067]
### Description

# Description

#2054 adds a report generation, exhaustively listing all snapshots in the Prettier test suite where the output of the Rome Formatter differs from Prettier. While precisely matching the output of Prettier is a non-goal this gives a baseline of ideas for various improvements that could be made to the formatter output, the goal of this umbrella issue is to triage all diffs in the report between formatting differences we wont be changing, and actual actionable tasks where we can improve the formatter output for a given case (with maybe a special case for formatting issues due to syntax we don't parse yet)

[Report as of Mar. 21 2022](https://gist.github.com/leops/b9ab972a9b9198a294d1c70a0c9b7185)

- [x] https://github.com/rome/tools/issues/2156
- [x] https://github.com/rome/tools/issues/2157
- [x] https://github.com/rome/tools/issues/2089
- [x] #2203
- [x] #2204

**Comment by MichaReiser** [comment]
This report is amazing! Thank you @leops for preparing it

**Comment by ematipico** [comment]
I am going to tackle the call expressions formatting. Other than the grouping thing, it's the other important formatting that we lack about.
