### ISSUE TITLE
☂️  Support TypeScript formatting 

### ISSUE THREAD

**Issue by ematipico** [rome/tools#2069]
# Objective

While the works on the [TypeScript parsing are on going](https://github.com/rome/tools/issues/1966), it's possible now starting working on supporting the formatting for TypeScript language.

In order to achieve that, the contributor needs first to check if the feature is actually supported by our parser. Also, the developer needs to check the error paths that aren't covered by the parser and try to avoid them for the time being.

Before working on something, please leave a comment here. Also, check the [`ungram` document](https://github.com/rome/tools/blob/main/xtask/codegen/js.ungram) to understand the grammar of the node.

## List of the nodes (and possible children nodes) to format*

- [x] [`TsTypeAliasStatement`](https://github.com/rome/tools/blob/main/xtask/codegen/js.ungram#L1513-L1519), this involves all the types that belong to `TsAnyType` @ematipico  #2070 
- [x] #2080 @ematipico 
- [x] [`TsTypeAssertionExpression`](https://github.com/rome/tools/blob/main/xtask/codegen/js.ungram#L1826-L1830)
- [x] [`TsAsExpression`](https://github.com/rome/tools/blob/main/xtask/codegen/js.ungram#L1832-L1835)
- [x] [`TsThisParameter`](https://github.com/rome/tools/blob/main/xtask/codegen/js.ungram#L1409-L1411)
- [x] [`TsTypeParameters`](https://github.com/rome/tools/blob/main/xtask/codegen/js.ungram#L1613-L1616)
- [x] [`TsAnyObjectTypeMember`](https://github.com/rome/tools/blob/main/xtask/codegen/js.ungram#L1643-L1650) 

*the position of the source code might change due to the on going works

**Comment by ematipico** [comment]
I am going to start the formatting of `TsEnumStatement`
