### ISSUE TITLE
☂️ Content changes before release

### ISSUE THREAD

**Issue by ematipico** [rome/tools#2183]
### Description

- [x] Update `README.md` with the current status of the project
- [x] #2184
- [x] #2279
- [x] Document formatter differences against most popular formatters (prettier, dprint)
- [x] #2280
- [x] Getting started guide with our VSCode extension
