### ISSUE TITLE
☂️ Automatic changelog creation

### ISSUE THREAD

**Issue by ematipico** [rome/tools#2339]
### Description

We are now in a stable situation, and we will start doing frequent releases. Our releases are automatically published and we don't have an automatic way to generate a changelog. 

This umbrella issue serves to track the tasks needed to achieve that:

- [ ] create a crate that interfaces with our VCS
- [ ] create a conventional commit parser to extract meaningful commits 
- [ ] create an xtask script that updates `CHANGELOG.md` with commits of latest release

Ideally we can call the new crate `rome_vcs`. We could have a struct that interfaces with git. We should leverage the crate [`git2`](https://github.com/rust-lang/git2-rs), maintained by the Rust lang itself.

**Comment by leops** [comment]
For now I would probably keep all of this in `xtask` (which is already interfacing with git in `codegen`) at least until we have something solid enough that would justify embedding `libgit2` into the Rome toolchain proper since its quite a heavy dependency.

The xtask script itself could be something more generic than just generating the changelog entry, like a `release` script that would also bump the version numbers and make sure everything is in place before releasing.

On the changelog itself GitHub seems to have an automatic release note generator, the `action-gh-release` action we're using to create the release on GitHub has a `generate_release_notes` option that makes use of it but that seems to work exclusively through the release creation API, it doesn't seem like something that can be used as a standalone feature.

**Comment by ematipico** [comment]
> For now I would probably keep all of this in xtask (which is already interfacing with git in codegen) at least until we have something solid enough that would justify embedding libgit2 into the Rome toolchain proper since its quite a heavy dependency.

Good point! I updated the description of the checklist. 

> On the changelog itself GitHub seems to have an automatic release note generator, the action-gh-release action we're using to create the release on GitHub has a generate_release_notes option that makes use of it but that seems to work exclusively through the release creation API, it doesn't seem like something that can be used as a standalone feature.

Well I think for now we can use it? Until we set up  a script that removes unwanted commits (like CI commits, etc.)

![Screenshot 2022-04-01 at 09 37 39](https://user-images.githubusercontent.com/602478/161227630-8e0264b3-682d-4d83-8e7b-3846a11d6457.png)

What do you think?
