### ISSUE TITLE
☂️ CSS support

### ISSUE THREAD

**Issue by ematipico** [rome/tools#2350]
### Description

We are going to use this issue to track the various work around CSS. We don't plan, for the time being, to support super languages, although we might think about preparing the infrastructure to be able to support them.

- [ ] create a `css.ungram` file where we will slowly implement new grammars
- [ ] create a `rome_css_syntax` crate, where we will have all things related to the CSS syntax, generated code too
- [ ] expand the codegen of the grammar to include CSS too
- [ ] evaluate how to implement the parser, lexer, etc. (it will require a separate discussion)
- [ ] create a `rome_css_formatter` crate
- [ ] make the `rome_formatter` generic
- [ ] prepare the Rome architecture to include CSS (file handlers, capabilities, etc.)
- [ ] add support for CSS inside the VSCode extension

**Comment by nstepien** [comment]
I was planning on enabling the Rome formatter with its next release to replace prettier in one of our repos, but I realized that CSS formatting, specifically css-in-js, isn't supported yet.

Very much looking forward to Rome having CSS formatting support!

**Comment by ematipico** [comment]
CSS-in-JS is still JavaScript, right? If so, then I believe that that the JS formatter should do that

**Comment by nstepien** [comment]
>CSS-in-JS is still JavaScript, right?

It depends on the css-in-js lib, in our case we use linaria so it looks like this:
```tsx
const myClass = css`
  color: red;
`;
```
which is plain CSS (without the topmost selector) in a template string.
I believe #2572 is related.

With some other libs like `vanilla-extract` it may be
```tsx
const myClass = style({
  color: 'red'
});
```
which is indeed plain js.

**Comment by ematipico** [comment]
> > CSS-in-JS is still JavaScript, right?
> 
> It depends on the css-in-js lib, in our case we use linaria so it looks like this:
> 
> ```tsx
> const myClass = css`
>   color: red;
> `;
> ```
> 
> which is plain CSS (without the topmost selector) in a template string. I believe #2572 is related.

I did a quick search, I think prettier call these cases "embedded" languages: 
https://github.com/prettier/prettier/blob/d13feed42b6478710bebbcd3225ab6f203a914c1/src/language-js/embed/css.js

And yes, they use a different parser/formatter inside these isntances. Thank you for pointing it out!

**Comment by BasixKOR** [comment]
Could we leverage [Lightning CSS](https://lightningcss.dev/) (and by extension [cssparser](https://docs.rs/cssparser/0.29.6/cssparser/)) to achieve this?

**Comment by ematipico** [comment]
> Could we leverage [Lightning CSS](https://lightningcss.dev/) (and by extension [cssparser](https://docs.rs/cssparser/0.29.6/cssparser/)) to achieve this?

We explored cssparser a bit. While it's a good starting point, unfortunately it doesn't fit very well our CST. I haven't done a lot of exploration work, but it seemed that retrieving trivia is not an easy task.

**Comment by denbezrukov** [comment]
I've started to implement a lexer for a css parser.
