### ISSUE TITLE
☂️ Documentation changes 0.5.0

### ISSUE THREAD

**Issue by ematipico** [rome/tools#2362]
### Description

- [ ] changes to `rome format` arguments and behaviour, now the default behaviour of the command is printing in the console
- [ ] update changelog with new features and breaking changes (format CLI now doesn't write by default, but it prints. Using `--write` will write to file)
- [ ] update website documentation for `--quote-style` option
