### ISSUE TITLE
☂️ Documentation changes 0.6.0

### ISSUE THREAD

**Issue by ematipico** [rome/tools#2506]
# Tentative release date, Tuesday 7th of June

List of changes to apply to the changelog and the website:
- [ ] **NEW**: Added the `rome check` CLI command to run the linter on a set of files / directories
- [ ] **BREAKING**: The `rome format --ci` command has been renamed to `rome ci`, and now includes linting as well
- [ ] **NEW**: Added a `--no-colors` global flag to the CLI to disable the formatting of markup
- [ ] Better compatibility with Prettier
	- Better formatting of various statements
	- Closed the majority of typescript formatting issue
	- Great work around string literals
