### ISSUE TITLE
Multi-Lang Formatter: Extract re-usable logic to `rome-formatter`

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2566]
## Goal

Build a language-agnostic infrastructure for formatting documents. 

## Tasks

* [x] Introduce new `formatted!` macro #2557
* [x] Move `Format`, `Formatter`, and `IntoFormatElement` to `rome_formatter` #2559
* [x] ~Refactor `space`, `group`... builders to return objects implementing `Format` (and introduce `format_args!` macro)~
* [x] Support language specific formatter options (Leaning towards making `FormatOptions` a trait and paremetrize `Format` with an `Option` type. #2578 
* [x] Move `format_node`, `format_range` to `rome_formatter`.  #2557

**Comment by MichaReiser** [comment]
I'm not going to implement the `space`, `group` etc. builders that accept a `Format`. It doesn't seem to play nice with our current approach where `Format` returns a `Result` rather than being able to do an imperative `write!`. 

The main challenge are patterns (that are quiet common)

```rust
if ... {
  formatted![formatter, space_token, argument.format()]?
} else {
  empty_element()
}
```

The only unified return type is `FormatElement` or `format_args` but `format_args` isn't an owned value, thus, cannot be returned from the branches. 

This works better with a model where the if can call into `write!` directly.
