### ISSUE TITLE
Multi-Lang Formatter: Code Gen Support

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2567]
## Goal 

Extend Rome's formatter codegen to support generating the source files for different languages

## Tasks

* [ ] Setup `rome_json_formatter` crate
* [ ] Generate the re-usable `AsFormat`, `IntoFormat`, `FormattedIter` (and `prelude`?) as part of the code gen. 
  * For example, by moving the implementation into a file in the code gen, then including it with `#include_str`. 
* [ ] Extend the codegen to generate the JSON formatter files and generate the default JSON formatter

## Dependencies

* Depends on #2566
