### ISSUE TITLE
Multi-Lang Formatter: Benchmark and Testing

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2568]
## Goal

Set up benchmarking and the test infra for the JSON formatter

## Tasks

* [x] Add Prettier's JSON spec tests and run them as part of the test suite #3913 
* [x] Find representative JSON files and run them as part of`bench_formatter` #3845 
* [ ] Add support for creating JSON formatter spec tests

## Dependencies

* [x] #2567

**Comment by MichaReiser** [comment]
@leops how did you add the Prettier tests? Do you have that script still somewhere with some instructions on how to run it?

**Comment by leops** [comment]
> @leops how did you add the Prettier tests? Do you have that script still somewhere with some instructions on how to run it?

The script I used is committed to the repo in [crates/rome_js_formatter/tests/specs/prettier/prepare_tests.js](https://github.com/rome/tools/blob/main/crates/rome_js_formatter/tests/specs/prettier/prepare_tests.js). It's really basic, all it does is look for certain patterns of Jest snapshots and extract them into individual files, but it should be possible to extend it from there
