### ISSUE TITLE
JSON Formatting

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2570]
## Goal

Support formatting JSON documents

## Tasks

* [x] Literal formatting
* [x] Object formatting
* [x] #4064
* [x] Number formatting (normalization of numbers, similar to JS implementation) @denbezrukov 
* [x] String formatting (normalization of escapes, similar to JS implementation) @denbezrukov 
* [ ] Enable JSON formatting in `rome_service`

(No comments, yay)

**Comment by IWANABETHATGUY** [comment]
Could you assign this to me ?

**Comment by DhrjArun** [comment]
Hi @MichaReiser I have been reading rome codebase for 2 weeks now. Can I work on this?

**Comment by MichaReiser** [comment]
> Hi @MichaReiser I have been reading rome codebase for 2 weeks now. Can I work on this?

Not yet. The JSON parser isn't implemented yet, and there's some infrastructure that must be set up. I'll be working on the JSON parsing in the next few weeks, hopefully, it will be ready by December to start implementing JSON formatting.

**Comment by DhrjArun** [comment]
ok, let me know if I could be of any help in implementing JSON parsing.

**Comment by MichaReiser** [comment]
> Hi @MichaReiser I have been reading rome codebase for 2 weeks now. Can I work on this?

@dhrjarun: @denbezrukov is setting up the test infra in #3913 and you could implement array formatting after that PR lands (and  @denbezrukov could work on objects)

**Comment by dhrjarun** [comment]
> > Hi @MichaReiser I have been reading rome codebase for 2 weeks now. Can I work on this?
> 
> @dhrjarun: @denbezrukov is setting up the test infra in #3913 and you could implement array formatting after that PR lands (and  @denbezrukov could work on objects)

Sure

**Comment by MichaReiser** [comment]
And #3913 is merged. Thank you @denbezrukov for your amazing work

**Comment by denbezrukov** [comment]
I guess that we need to keep it open because we still need to implement array formatting.

**Comment by ematipico** [comment]
@denbezrukov 

This issue was closed because your last PR contained a [magic comment](https://github.blog/2013-01-22-closing-issues-via-commit-messages/):
> Fix https://github.com/rome/tools/issues/2570 for Object value.

**Comment by MichaReiser** [comment]
@dhrjarun do you plan to work on the array formatting or are you OK if someone else starts the work?

**Comment by dhrjarun** [comment]
@MichaReiser I will send pr tomorrow.

**Comment by MichaReiser** [comment]
There are two more tasks. Normalization of string and number literals, similar to how it is done in the JS implementation.

**Comment by denbezrukov** [comment]
Can I take it?

**Comment by MichaReiser** [comment]
> Can I take it?

Sure!
