### ISSUE TITLE
📎 Printer & IR Capabilities

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2579]
### Description

The goal of this task is to track missing Formatter IR elements and behaviour differences to Prettier. 

## Different Semantics
* [x] Group printing:`fits` #2598
* [x] Fill

## Rome only IR

Evaluate if indeed necessary

* [x] HardGroup #2597 

## Missing IR Elements
The goal isn't to implement all these IR elements. We should only implement them if necessary 

- [ ] `align`/ `dedent` / `dedentToRoot`, `markAsRoot`
- [ ] `indentIfBreak`: Optimized version of `ifBreak(indent)` unclear what’s optimized about it because it creates an `indent` element inside of the printer.
- [x] Conditional Groups (Alternatives) #2529 #2591
- [x] `LineSuffixBoundary` #2590
- [x] `BreakParent` #2590
    - Forces to break the parent group (except if it’s a conditional group with expanded states)
    - Implemented as a traversal before the print, navigates through the document and sets `group.break` to `propagated` on the parent group
- [x] `ifBreak`/ `group` with `groupId` #2589
    - Allows adding conditional logic depending on if a specific parent group breaks (not necessarily the direct parent)
- [ ] `trim`

**Comment by MichaReiser** [comment]
Here some notes from my research

# Prettier IR / Printer Differences

Tags: Projects

This document describes the differences between Rome’s and Prettier’s printer and IR.

# Differences

## Group

### `fits`

Rome’s `fits` tries to print the whole group including all it’s content on a single line. The group fits if all tokens up the last token of the outmost “flat” group fit inside of the print width.

This is different to Prettier’s `fits` definition because

- A hard-line break doesn’t break a group, instead:
- a group fits if the content of the group and any content following the group up to the first hard line break fits on the line.
- Flat groups can contain expanded groups (with `break: true`).

The definition is the same in regards that if a child group expands, then the parent groups expand and the printer tries to re-print with the outer-most group expanded.

```jsx
let document1 = builders.group([
	"A somewhat long string that must be ",
	builders.softline,
	"grouped",
	builders.hardline,
	builders.group("grouped and should exceed the print with of 86"),
]);
```

Prints to 

```jsx
A somewhat long string that must be grouped
grouped and should exceed the print with of 86
```

vs Rome

```jsx
A somewhat long string that must be 
grouped
grouped and should exceed the print with of 86
```

### `break`

Prettier’s `group` IR has a `break` option (called `shouldBreak` in the builder API). If set to `true`, then the printer prints this group in “expanded” mode, printing soft line breaks as hard line breaks. 

This can change the printer’s output compared to when the group isn’t present because `fits` determines if the content up to the first line break fits on a single line, and soft line breaks now become hard line breaks. 

That’s why these two documents have the same behavior

```jsx
builders.group([
 	"A somewhat long string that must be ",
 	builders.softline, // Get's turned into a hard line break because of the break parent
 	"grouped",
 	builders.group(
 		[
 			"and should exceed",
 			builders.softline, // Becomes a hard line break
 			" the print with of 86",
 		],
 		{ shouldBreak: true },
 	),
]);

builders.group([
	"A somewhat long string that must be ",
	builders.softline, // Get's turned into a hard line break because of the break parent
	"grouped",
	"and should exceed",
	builders.hardline,
	" the print with of 86",
]);
```

Which prints (only breaks at the hard-line break)

```jsx
A somewhat long string that must be groupedand should exceed
 the print with of 86
```

Therefore, `break` is syntactic sugar to simplify the construction of IR elements because it’s otherwise necessary to re-write the whole sub-tree to replace all `softline` and `softline_with_space` with `hardline`. 

### Must be Flat

Prettiers fitting logic changes for `fill` because it forces that the output must be flat, meaning that the algorithm returns `false` for a `group` with `break: true` (Interestingly, not if it encounters a hard line break)

## Fill

Prettier’s fill assumes that the `fill` content is an alternating list of `element` and `line-break`s whereas Rome’s printer assumes that elements must always be separated by spaces. 

Prettier’s IR is more flexible in the sense that it also supports `fill` for cases where the element should be separated by a line break if they don’t fit, but otherwise isn’t separated. A use case for this is when joining `JsxText`. 

→ Extend the `fill` API to provide a custom separator 

# Missing IR Elements

- `align`/ `dedent` / `dedentToRoot`, `markAsRoot`
- `indentIfBreak`: Optimized version of `ifBreak(indent)` unclear what’s optimized about it because it creates an `indent` element inside of the printer.
- Conditional Groups (Alternatives)
- `LineSuffixBoundary`
    - 
- `BreakParent`
    - Forces to break the parent group (except if it’s a conditional group with expanded states)
    - Implemented as a traversal before the print, navigates through the document and sets `group.break` to `propagated` on the parent group
- `ifBreak`/ `group` with `groupId`
    - Allows adding conditional logic depending on if a specific parent group breaks (not necessarily the direct parent)
- `trim`

## Resources

- [https://github.com/prettier/prettier/blob/main/commands.md](https://github.com/prettier/prettier/blob/main/commands.md)

**Comment by MichaReiser** [comment]
Some corrections to what I've written above:

* `breakParent` doesn't only break the current parent but breaks all ancestor groups. 
* Prettier has two builders to create `hardline` *elements*`. The default always inserts a `breakParent`, thus, it matches the behaviour of our `hardline` element. Meaning, the main difference is how Prettier and Rome compute if a group "fits". Prettier doesn't only consider the group but also the width of the elements following in the document. 

I have an implementation that changes the `fits` definition, and adds the `breakParent` and `lineSuffixBoundary` IR instructions. The main issue is that `HardGroup` doesn't play nicely with this adjusted behaviour and there are multiple issues where comments get moved (rather far). So it seems, we first need to re-visit how we print comments.

**Comment by MichaReiser** [comment]
Alright, I'm going to split this into the following smaller PRs. Let's see if I encounter any additional cycles. 

1. Rewrite our `Printer` to use a `fits` function similar to Prettier's. The needed because testing if a variant fits must return `true` if the variant contains line breaks that aren't part of a "flat" group.
2. Introduce `AlternativeGroup`, `shouldBreak` on `Group`, and `breakParent`. This should allow to remove some usages of `HardGroup`
3. Remove `HardGroup` by printing all inline comments in the same spot as they used to be. Add `LineSuffixBoundary` to have a mechanism to flush pending comments. 
4. Change printer `fits` to only return `true` if the `group` andy any content following it fits on the line
5. Revisit comments printing

I'm not sure if I'll manage to keep 2/3 separate but let me try.

**Comment by MichaReiser** [comment]
I'm closing this for now. We can add the additional IR elements when we need them for the first time. This is probably better than implementing all of them upfront without having any real use case.
