### ISSUE TITLE
☂️ Rome classic lint rules, with scoping

### ISSUE THREAD

**Issue by ematipico** [rome/tools#2743]
# Note

***This rules should be implemented once https://github.com/rome/tools/issues/2488 is closed***.

This is because in order to correctly implement the rule, there's need to have access to the scope.

# If you want to contribute
1. make sure you understand the requirements of the rule you would like to implement;
3. comment on this very issue telling saying which rule you would like to implement;
4. create a new task issue and link to this very umbrella issue (a member of the team will eventually assign it to you);
5. open a PR;

> **Note**: please make sure to comment the issue saying which rule you'd like to implement, this would allow better coordination between contributors. Failing to do so would penalize yourselves against contributors that had followed these simple guildelines

> **Note**: follow the naming convention guidelines: https://github.com/rome/tools/blob/archived-js/CONTRIBUTING.md#naming-patterns

# List of rules that might require scoping resolution

- [x] #2903
- [x] `noUnusedVariables`: https://github.com/rome/tools/blob/archived-js/website/src/docs/lint/rules/js/noUnusedVariables.md
- [x] #3292
- [x] #3267
- [x] #3204
- [x] #3313
- [x] ~`noRedundantShouldComponentUpdate`: https://github.com/rome/tools/blob/archived-js/website/src/docs/lint/rules/react`/noRedundantShouldComponentUpdate.md~ Deprecated
- [x] #3248
- [x] #3254
- [x] #3272
- [x] #3233
- [x] #3278
- [x] ~`useInterfaces`: https://github.com/rome/tools/blob/archived-js/website/src/docs/lint/rules/ts/useInterfaces.md 
	This rule was removed from Rome classic. We should consider it with care~ too pedantic, not needed
- [x] `noArguments`: #2807
- [x] https://github.com/rome/tools/issues/2848
- [x] #2878
- [x] `noImportAssign`: https://github.com/rome/tools/blob/archived-js/website/src/docs/lint/rules/js/noImportAssign.md
- [x] #2837
- [x] #3341
- [x] #3338
- [x] #2897
- [x] #2836
- [x] #3281
- [x] ~`noFindDOMNode`: https://github.com/rome/tools/blob/archived-js/website/src/docs/lint/rules/react/noFindDOMNode.md~

> **Note**: this rule requires access to the filename, which is not implemented yet
- [x] ~[useDefaultExportBasename](https://github.com/rome/tools/blob/archived-js/website/src/docs/lint/rules/js/useDefaultExportBasename.md)~
Enforce the name of the file and the name of the default function / class export matches
- [x] ~https://github.com/rome/tools/issues/2754~ (requires parsing of regex)
- [x] ~https://github.com/rome/tools/issues/2753~ 
	> At the moment the linter lacks two capabilities requires to implement this, the first and most important is the ability for lint rules (and visitors) to inspect syntax tokens (currently lint rules can only query AST nodes), while a secondary one would be to allow rules to be enabled or disabled on a per-language basis: currently the existing JSX and TS rules are enabled all the time which isn't really a problem since they only query node for their language and thus never match in incompatible files, but if this rule needs to inspect all tokens we would want it to be disabled on non-TS files.
- [x] ~https://github.com/rome/tools/issues/2755~ (might be implemented in the formatter)

**Comment by Conaclos** [comment]
All links seem dead.

**Comment by ematipico** [comment]
> Some links are dead.

Thank you! They should be fixed now

**Comment by IWANABETHATGUY** [comment]
@ematipico would you mind assigning me task `noCatchAssign`?

**Comment by IWANABETHATGUY** [comment]
@ematipico , would you mind assigning me the task `noImportAssign`?  Related issue https://github.com/rome/tools/issues/2923

**Comment by IWANABETHATGUY** [comment]
`noImportAssign` is already merged.

**Comment by ematipico** [comment]
I will work on `useButtonType`

**Comment by ematipico** [comment]
The rule `noFindDOMNode` was mainly a warning of using an API meant to be deprecated. [The API is now deprecated](https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage), so maybe we don't need this rule anymore
