### ISSUE TITLE
☂️ Documentation changes 0.8.0

### ISSUE THREAD

**Issue by ematipico** [rome/tools#2835]
# Tentative date, 2th August 2022

- NEW: configuration file available for formatter
- NEW: `--max-diagnostics` for `rome check`
- NEW: `rome init` command
- NEW: configuration file available for linter
- NEW: renaming symbol feature available VSCode

# Nice to have features
- [x] rules divided per category (`js`, `jsx`, `react`, etc.);
- [x] add the version number to the documentation of rules, so we can have something like:
	```md
	# noUnusedVariable (since v0.8.0)
	```
- [x] semantic model to use inside lint rules;
- [x] limit diagnostics to 10 by default, have an argument for `rome check` to change the number of diagnostics: `--max-diagnostics`
