### ISSUE TITLE
☂️ Analyzer Correctness

### ISSUE THREAD

**Issue by xunilrj** [rome/tools#3038]
### Description

This is an umbrella issue to improve the Analyzer correctness.

- [x] Increase automated coverage of the linter;
- [x] Run the analyzer against git repositories;
- [ ] Being able to track times for single rules;
- [ ] Run existing rules against the Rome classic code base;
- [ ] Run the semantic model as part of t262 tests;
- [ ] Move parser checks/diagnostics inside lint rules

**Comment by ematipico** [comment]
@xunilrj could you please tick the task that have been implemented? 

As far as I understood the correctness project came to end, so should we close the issue?

**Comment by xunilrj** [comment]
I created a discussion for "Being able to track times for single rules;" https://github.com/rome/tools/discussions/3127 but we have not decided to go with this solution.
