### ISSUE TITLE
☂️ Formatter 0.9.0 

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3046]
### Description

This is an umbrella issue for the work on the Formatter for the 0.9.0 release. 

## Goals

* Rome removes unnecessary parentheses and adds parentheses to improve readability. 
* Improve Prettier compatibility of some core syntax nodes. 

## Tasks 

* [x] Parentheses (2 weeks) #2427 
  * [x] Implement parentheses handling for expressions  #3057, #3079 #2449 
  * [x] Implement parentheses handling for assignments #3083 
  * [x] Implement parentheses handling for types #3108
  * [x] Remove parenthesized nodes from formatting tree #3092
* [x] Prettier compatibility (2 weeks)
  * [x] `JsConditionalExpression`
  * [x] Hug function parameters
  * [x] Parameter and return type formatting
  * [x] return and throw argument
  * [x] `JsTemplate`  #2446 #3063
  * [x] `JsBinaryExpression` #3079
  * [x] `JsArrowFunctionExpression` #3122 
  * [x] `JsArrayExpression` #3126
  * [x] `JsStaticMemberAssignment` and `JsComputedMemberAssignment` #3061
  * [x] JSX formatting #3144
  * [x] JSX in Conditional Expressions #3150

**Comment by ematipico** [comment]
This is a follow up question after https://github.com/rome/tools/pull/3057.

Is there a specific reason why the "needs parentheses" information is tracked inside the formatter phase?

Have considered some other solutions, such as a visitor approach, or even computing this information during the parsing phase and storing it inside our green tree?

I would like to know what are the implications of your decisions in the future developments

**Comment by MichaReiser** [comment]
@ematipico I [replied](https://github.com/rome/tools/pull/3057#issuecomment-1214664439) on the PR as these questions seem relevant to the implementation.

**Comment by MichaReiser** [comment]
I start working on the Arrow function formatting

**Comment by MichaReiser** [comment]
I'll start looking into JSX formatting tomorrow

**Comment by IWANABETHATGUY** [comment]
We are getting close to 90% prettier compatibility, that's awesome.
