### ISSUE TITLE
☂️ Formatter 0.10.0

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3047]
### Description

# Goals 

* Stable comments formatting #2664 
* Improve Prettier compatibility 

### Comments (~2 weeks)
* [x] Pre-process AST and extract comments 
* [x] Improve comments placement 

### Prettier Compatibility (~1 week)

**High Priority**

* [x] Call Chain / Method chain #3273 
* [x] Call arguments #3290 
* [x] first argument expansion #3290 
* [x] last argument expansion #3290 

**Bugs**
* [ ] JSX Spaces https://github.com/rome/tools/issues/3211 and [playground](https://play.rome.tools/?code=export+default+function+MapEditor%28%29%3A+JSX.Element+%7C+null+%7B%0A++return+%28%0A++++%3Cdiv%3E%0A++++++%3Cdiv+%2F%3E%7B%22+%22%7D%0A++++%3C%2Fdiv%3E%0A++%29%3B%0A%7D&lineWidth=80&indentStyle=tab&quoteStyle=single&quoteProperties=as-needed&indentWidth=2&sourceType=module&typescript=true&jsx=true#ZQB4AHAAbwByAHQAIABkAGUAZgBhAHUAbAB0ACAAZgB1AG4AYwB0AGkAbwBuACAATQBhAHAARQBkAGkAdABvAHIAKAApADoAIABKAFMAWAAuAEUAbABlAG0AZQBuAHQAIAB8ACAAbgB1AGwAbAAgAHsACgAgACAAcgBlAHQAdQByAG4AIAAoAAoAIAAgACAAIAA8AGQAaQB2AD4ACgAgACAAIAAgACAAIAA8AGQAaQB2ACAALwA+AHsAIgAgACIAfQAKACAAIAAgACAAPAAvAGQAaQB2AD4ACgAgACAAKQA7AAoAfQA=)

**Best Effort**
* [x] #3162
* [ ] Export: Respect empty lines

**Comment by denbezrukov** [comment]
@MichaReiser Hi!
I can try to help you with TS Intersection. 

https://github.com/prettier/prettier/blob/68bd87b24ba00049ac74870de75596639fd967bb/src/language-js/print/type-annotation.js#L94-L120

**Comment by MichaReiser** [comment]
> @MichaReiser Hi! I can try to help you with TS Intersection.
> 
> [prettier/prettier@`68bd87b`/src/language-js/print/type-annotation.js#L94-L120](https://github.com/prettier/prettier/blob/68bd87b24ba00049ac74870de75596639fd967bb/src/language-js/print/type-annotation.js#L94-L120)

Whoos sorry. I missed this message. That would be awesome!

**Comment by nstepien** [comment]
Really hoping for a trailing commas option, it's the biggest difference with Prettier for us. 🙏 
https://prettier.io/docs/en/options.html#trailing-commas

**Comment by cpojer** [comment]
Here are a few more inconsistencies: https://github.com/rome/tools/issues/3178.

**Comment by MichaReiser** [comment]
If anyone is interested having a look at the JSX spacing issues, let me know.

**Comment by MichaReiser** [comment]
> Really hoping for a trailing commas option, it's the biggest difference with Prettier for us. pray [prettier.io/docs/en/options.html#trailing-commas](https://prettier.io/docs/en/options.html#trailing-commas)

We're considering adding the `trailing-comma` `es5` option which is the default in Prettier today. Would this be sufficient for your use case or are you using `none`?
