### ISSUE TITLE
☂️ Tracking issues or potential improvement we could make after upgrades to the Rust toolchain

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rome/tools#3054]
# Task
## Issues after upgrade to 1.63.0
- [x] rustdoc::broken_intra_doc_links can't detect the `macro_export` 
- [ ] let_and_return rule will cause a borrow checker issue.

## Potential improvements we could make
- [x] ~From Rust 1.64: Cargo now supports inheriting some package attributes from the workspace (see https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table for the list of supported attributes), we could move some of the attributes currently duplicated between all crates (like `authors`, `repository`, `licence` or `edition`) to the root `Cargo.toml` file~
- [x] From Rust 1.63: With the standard library Mutex and RwLock being const-constructible it's now possible to use these in the DiffReport of the Prettier test suite
- [x] From Rust 1.62 it's now possible to derive the Default trait on enums, we could track down and remove the manual implementations for these
- [x] ~From Rust 1.61 the Termination trait and ExitCode type are now stable, meaning we could implement stable exit codes for the CLI (this could be done in the incoming refactor of diagnostics)~

**Comment by IWANABETHATGUY** [comment]
rustdoc::broken_intra_doc_links : https://github.com/rome/tools/pull/3053#discussion_r944105018
let_and_return : https://github.com/rome/tools/pull/3053#discussion_r944102789

**Comment by ematipico** [comment]
Hi @IWANABETHATGUY , could you please update the description and explain what's this umbrella for?

**Comment by leops** [comment]
> Hi @IWANABETHATGUY , could you please update the description and explain what's this umbrella for?

I think we may "refactor" this umbrella to track both issues that are introduced in upgrades to the Rust toolchain (mostly Clippy false positives), and possible improvements to the existing codebase made possible by newly stabilized APIs (I came up with a short list of these here: https://github.com/rome/tools/pull/3053#issuecomment-1212812230)

**Comment by IWANABETHATGUY** [comment]
> 

Done

**Comment by ematipico** [comment]
Someone already filed an issue for the false positive of `let_and_return`: `https://github.com/rust-lang/rust-clippy/issues/8114
