### ISSUE TITLE
☂️ Lint rules from other sources 10.0.0

### ISSUE THREAD

**Issue by ematipico** [rome/tools#3358]
### Description

The team has selected the following additional rules to implement for the `10.0.0` release.

They have been selected from https://github.com/rome/tools/discussions/3357

If the team is able to implement all of them before the release of `10.0.0`, other rules will be added.

- From `eslint`
    - `prefer-numeric-literals` [https://eslint.org/docs/rules/prefer-numeric-literals](https://eslint.org/docs/rules/prefer-numeric-literals)
    - `constructor-super` [https://eslint.org/docs/rules/constructor-super](https://eslint.org/docs/rules/constructor-super)
    - `for-direction` [https://eslint.org/docs/rules/for-direction](https://eslint.org/docs/rules/for-direction)
    - `no-const-assign` [https://eslint.org/docs/rules/no-const-assign](https://eslint.org/docs/rules/no-const-assign)
    - `no-dupe-keys` [https://eslint.org/docs/rules/no-dupe-keys](https://eslint.org/docs/rules/no-dupe-keys)
- From `typescript/eslint`
    - `ban-types` [https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/ban-types.md?rgh-link-date=2022-06-20T13%3A52%3A50Z](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/ban-types.md?rgh-link-date=2022-06-20T13%3A52%3A50Z)
    - `no-explicit-any` [https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-explicit-any.md?rgh-link-date=2022-06-20T13%3A52%3A50Z](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-explicit-any.md?rgh-link-date=2022-06-20T13%3A52%3A50Z)
- From `clippy`
    - `map_flatten` [https://rust-lang.github.io/rust-clippy/master/#map_flatten](https://rust-lang.github.io/rust-clippy/master/#map_flatten)
    - `match_str_case_mismatch` [https://rust-lang.github.io/rust-clippy/master/#match_str_case_mismatch](https://rust-lang.github.io/rust-clippy/master/#match_str_case_mismatch)

**Comment by IWANABETHATGUY** [comment]
Would you mind assigning me the task `prefer-numeric-literals`?

**Comment by ematipico** [comment]
> Would you mind assigning me the task `prefer-numeric-literals`?

Sure! Please leave a comment in the issue so I can assign it to you

**Comment by xunilrj** [comment]
More details about

 https://github.com/rome/tools/pull/3355
Checks the dependencies array of React Hooks contains all referenced bindings
Example error:
function Component({ prop }) { useEffect(() => { prop(); }, []); }

 - [ ] Missing dependencies;
 - [ ]  Extra dependencies;
 - [ ]  Consider some React hooks returns as stable;
 - [ ] Consider const a = <some constant> as stable;
 - [ ] Consider declarations inside the React component that are potentially capturing non-stable variables.
 - [ ] Incorporate eslint tests
 - [ ] improved configuration
 - [ ] Correctly suggest dependencies for properties: "a.b" and "a.c" instead of "a"
 - [ ] Correctly deal with globals and undefined dependencies

**Comment by DerGernTod** [comment]
i didn't find any issue that would fit this comment better: are you planning to support custom linting rules? we have a lot of very project-specific linting rules we wrote on our own (we have our internal linting rule package), and for eslint there's lots of third party linting packages out there (e.g. https://github.com/getify/eslint-plugin-proper-arrows/)

**Comment by ematipico** [comment]
> i didn't find any issue that would fit this comment better: are you planning to support custom linting rules? we have a lot of very project-specific linting rules we wrote on our own (we have our internal linting rule package), and for eslint there's lots of third party linting packages out there (e.g. [getify/eslint-plugin-proper-arrows](https://github.com/getify/eslint-plugin-proper-arrows/))

It's something that we want to support, but on the other hand it's not something that is easily implementable; we are investigating how to to use V8 as runtime, then we will need to investigate how to add new rules, dynamically. Nowadays it's not even possible using the Rust API because the infrastructure doesn't allow it.
