### ISSUE TITLE
☂️ [PAUSED] React lint rules

### ISSUE THREAD

**Issue by sebmck** [rome/tools#341]
This issue serves to discuss what React rules we should have in Rome. Ideally these rules would be blessed by the React team.

What rules do you think are the most important? Keep in mind that Rome does not allow disabling lint rules. You can only suppress them. The React rules will not be an exception. Rome allows AST autofixes which drastically simplifies the existence of many lint rules by allowing them to be automatically fixed, and with the Rome review system, unsafe suggestions are also easily added and amended.

**Comment by sebmck** [comment]
It would be nice to have a strong set of accessibility rules. We could have autofixes/suggestions that infer from usage what props the author probably meant.

**Comment by Daniel15** [comment]
FWIW here's the list of lint rules included with Create React App, which is probably a good guide as to which rules a lot of people are using today: https://github.com/facebook/create-react-app/blob/master/packages/eslint-config-react-app/index.js

The "Rules of Hooks" rule is a pretty important one for React hooks: https://github.com/facebook/react/tree/master/packages/eslint-plugin-react-hooks

> It would be nice to have a strong set of accessibility rules. 

Create React App uses `eslint-plugin-jsx-a11y` which seems to have some decent rules: https://github.com/evcohen/eslint-plugin-jsx-a11y/

**Comment by jamiebuilds** [comment]
Here's a list of all the potential rules, with info on what if they are in the "recommended" set and what their setting is in Create React App:

## React rules

- [ ] [react/boolean-prop-naming](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/boolean-prop-naming.md): Enforces consistent naming for boolean props
- [ ] [react/button-has-type](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/button-has-type.md): Forbid "button" element without an explicit "type" attribute
- [ ] [react/default-props-match-prop-types](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/default-props-match-prop-types.md): Enforce all defaultProps are defined and not "required" in propTypes.
- [ ] [react/destructuring-assignment](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/destructuring-assignment.md): Enforce consistent usage of destructuring assignment of props, state, and context
- [ ] [react/display-name](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/display-name.md): Prevent missing displayName in a React component definition **Recommended**
- [ ] [react/forbid-component-props](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-component-props.md): Forbid certain props on components
- [ ] [react/forbid-dom-props](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-dom-props.md): Forbid certain props on DOM Nodes
- [ ] [react/forbid-elements](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-elements.md): Forbid certain elements
- [ ] [react/forbid-foreign-prop-types](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-foreign-prop-types.md): Forbid using another component's propTypes *(CRA: Warn)*
- [ ] [react/forbid-prop-types](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-prop-types.md): Forbid certain propTypes
- [ ] [react/function-component-definition](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/function-component-definition.md): Standardize the way function component get defined (fixable)
- [ ] [react/no-access-state-in-setstate](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-access-state-in-setstate.md): Reports when this.state is accessed within setState
- [ ] [react/no-adjacent-inline-elements](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-adjacent-inline-elements.md): Prevent adjacent inline elements not separated by whitespace.
- [ ] [react/no-array-index-key](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-array-index-key.md): Prevent usage of Array index in keys
- [ ] [react/no-children-prop](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-children-prop.md): Prevent passing of children as props. **Recommended**
- [ ] [react/no-danger](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-danger.md): Prevent usage of dangerous JSX props
- [ ] [react/no-danger-with-children](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-danger-with-children.md): Report when a DOM element is using both children and dangerouslySetInnerHTML **Recommended** *(CRA: Warn)*
- [ ] [react/no-deprecated](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-deprecated.md): Prevent usage of deprecated methods **Recommended** *(CRA: Disabled because of undesirable warnings)*
- [ ] [react/no-did-mount-set-state](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-did-mount-set-state.md): Prevent usage of setState in componentDidMount
- [ ] [react/no-did-update-set-state](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-did-update-set-state.md): Prevent usage of setState in componentDidUpdate
- [ ] [react/no-direct-mutation-state](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-direct-mutation-state.md): Prevent direct mutation of this.state **Recommended** *(CRA: Warn)*
- [ ] [react/no-find-dom-node](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-find-dom-node.md): Prevent usage of findDOMNode **Recommended**
- [ ] [react/no-is-mounted](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-is-mounted.md): Prevent usage of isMounted **Recommended** *(CRA: Warn)*
- [ ] [react/no-multi-comp](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-multi-comp.md): Prevent multiple component definition per file
- [ ] [react/no-redundant-should-component-update](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-redundant-should-component-update.md): Flag shouldComponentUpdate when extending PureComponent
- [ ] [react/no-render-return-value](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-render-return-value.md): Prevent usage of the return value of React.render **Recommended**
- [ ] [react/no-set-state](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-set-state.md): Prevent usage of setState
- [ ] [react/no-string-refs](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-string-refs.md): Prevent string definitions for references and prevent referencing this.refs **Recommended**
- [ ] [react/no-this-in-sfc](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-this-in-sfc.md): Report "this" being used in stateless components
- [ ] [react/no-typos](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-typos.md): Prevent common typos *(CRA: Warn)*
- [ ] [react/no-unescaped-entities](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unescaped-entities.md): Detect unescaped HTML entities, which might represent malformed tags **Recommended**
- [ ] [react/no-unknown-property](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unknown-property.md): Prevent usage of unknown DOM property (fixable) **Recommended**
- [ ] [react/no-unsafe](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unsafe.md): Prevent usage of unsafe lifecycle methods
- [ ] [react/no-unused-prop-types](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unused-prop-types.md): Prevent definitions of unused prop types
- [ ] [react/no-unused-state](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unused-state.md): Prevent definition of unused state fields
- [ ] [react/no-will-update-set-state](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-will-update-set-state.md): Prevent usage of setState in componentWillUpdate
- [ ] [react/prefer-es6-class](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prefer-es6-class.md): Enforce ES5 or ES6 class for React Components
- [ ] [react/prefer-read-only-props](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prefer-read-only-props.md): Require read-only props. (fixable)
- [ ] [react/prefer-stateless-function](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prefer-stateless-function.md): Enforce stateless components to be written as a pure function
- [ ] [react/prop-types](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md): Prevent missing props validation in a React component definition **Recommended**
- [ ] [react/react-in-jsx-scope](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/react-in-jsx-scope.md): Prevent missing React when using JSX **Recommended** *(CRA: Warn)*
- [ ] [react/require-default-props](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/require-default-props.md): Enforce a defaultProps definition for every prop that is not a required prop.
- [ ] [react/require-optimization](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/require-optimization.md): Enforce React components to have a shouldComponentUpdate method
- [ ] [react/require-render-return](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/require-render-return.md): Enforce ES5 or ES6 class for returning value in render function **Recommended** *(CRA: Error)*
- [ ] [react/self-closing-comp](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/self-closing-comp.md): Prevent extra closing tags for components without children (fixable)
- [ ] [react/sort-comp](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md): Enforce component methods order
- [ ] [react/sort-prop-types](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-prop-types.md): Enforce propTypes declarations alphabetical sorting
- [ ] [react/state-in-constructor](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/state-in-constructor.md): State initialization in an ES6 class component should be in a constructor
- [ ] [react/static-property-placement](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/static-property-placement.md): Defines where React component static properties should be positioned.
- [ ] [react/style-prop-object](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/style-prop-object.md): Enforce style prop value is an object *(CRA: Warn)*
- [ ] [react/void-dom-elements-no-children](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/void-dom-elements-no-children.md): Prevent passing of children to void DOM elements (e.g. `<br />`).

## JSX-specific rules

- [ ] [react/jsx-boolean-value](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-boolean-value.md): Enforce boolean attributes notation in JSX (fixable)
- [ ] [react/jsx-child-element-spacing](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-child-element-spacing.md): Ensures inline tags are not rendered without spaces between them
- [ ] [react/jsx-closing-bracket-location](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-closing-bracket-location.md): Validate closing bracket location in JSX (fixable)
- [ ] [react/jsx-closing-tag-location](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-closing-tag-location.md): Validate closing tag location for multiline JSX (fixable)
- [ ] [react/jsx-curly-brace-presence](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-curly-brace-presence.md): Disallow unnecessary JSX expressions when literals alone are sufficient or enfore JSX expressions on literals in JSX children or attributes (fixable)
- [ ] [react/jsx-curly-newline](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-curly-newline.md): Enforce consistent line breaks inside jsx curly (fixable)
- [ ] [react/jsx-curly-spacing](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-curly-spacing.md): Enforce or disallow spaces inside of curly braces in JSX attributes (fixable)
- [ ] [react/jsx-equals-spacing](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-equals-spacing.md): Disallow or enforce spaces around equal signs in JSX attributes (fixable)
- [ ] [react/jsx-filename-extension](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-filename-extension.md): Restrict file extensions that may contain JSX
- [ ] [react/jsx-first-prop-new-line](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-first-prop-new-line.md): Ensure proper position of the first property in JSX (fixable)
- [ ] [react/jsx-fragments](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-fragments.md): Enforce shorthand or standard form for React fragments (fixable)
- [ ] [react/jsx-handler-names](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-handler-names.md): Enforce event handler naming conventions in JSX
- [ ] [react/jsx-indent](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-indent.md): Validate JSX indentation (fixable)
- [ ] [react/jsx-indent-props](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-indent-props.md): Validate props indentation in JSX (fixable)
- [ ] [react/jsx-key](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-key.md): Report missing `key` props in iterators/collection literals **Recommended**
- [ ] [react/jsx-max-depth](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-max-depth.md): Validate JSX maximum depth
- [ ] [react/jsx-max-props-per-line](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-max-props-per-line.md): Limit maximum of props on a single line in JSX (fixable)
- [ ] [react/jsx-no-bind](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md): Prevents usage of Function.prototype.bind and arrow functions in React component props
- [ ] [react/jsx-no-comment-textnodes](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-comment-textnodes.md): Comments inside children section of tag should be placed inside braces **Recommended** *(CRA: Warn)*
- [ ] [react/jsx-no-duplicate-props](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-duplicate-props.md): Enforce no duplicate props **Recommended** *(CRA: Warn)*
- [ ] [react/jsx-no-literals](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-literals.md): Prevent using string literals in React component definition
- [ ] [react/jsx-no-script-url](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-script-url.md): Forbid `javascript:` URLs
- [ ] [react/jsx-no-target-blank](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-target-blank.md): Forbid target="_blank" attribute without rel="noopener noreferrer" **Recommended** *(CRA: Warn)*
- [ ] [react/jsx-no-undef](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-undef.md): Disallow undeclared variables in JSX **Recommended** *(CRA: Error)*
- [ ] [react/jsx-no-useless-fragment](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-useless-fragment.md): Disallow unnecessary fragments (fixable)
- [ ] [react/jsx-one-expression-per-line](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-one-expression-per-line.md): Limit to one expression per line in JSX (fixable)
- [ ] [react/jsx-pascal-case](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-pascal-case.md): Enforce PascalCase for user-defined JSX components *(CRA: Warn, allowAllCaps: true, ignore: [])*
- [ ] [react/jsx-props-no-multi-spaces](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-props-no-multi-spaces.md): Disallow multiple spaces between inline JSX props (fixable)
- [ ] [react/jsx-props-no-spreading](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-props-no-spreading.md): Prevent JSX prop spreading
- [ ] [react/jsx-sort-default-props](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-sort-default-props.md): Enforce default props alphabetical sorting
- [ ] [react/jsx-sort-props](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-sort-props.md): Enforce props alphabetical sorting (fixable)
- [ ] [react/jsx-space-before-closing](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-space-before-closing.md): Validate spacing before closing bracket in JSX (fixable)
- [ ] [react/jsx-tag-spacing](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-tag-spacing.md): Validate whitespace in and around the JSX opening and closing brackets (fixable)
- [ ] [react/jsx-uses-react](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-uses-react.md): Prevent React to be marked as unused **Recommended** *(CRA: Warn)*
- [ ] [react/jsx-uses-vars](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-uses-vars.md): Prevent variables used in JSX to be marked as unused **Recommended** *(CRA: Warn)*
- [ ] [react/jsx-wrap-multilines](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-wrap-multilines.md): Prevent missing parentheses around multilines JSX (fixable)

**Comment by sebmck** [comment]
A lot of those seems so superfluous. We can pretty much ignore any of the rule that are specific to createClass. Also there’s many there that just get around ESLints poor handling of JSX, that we already handle such as variables in JSX being marked as used.

**Comment by ljharb** [comment]
There’s also the Airbnb config’s react rules worth considering.

**Comment by diokey** [comment]
Are react specific rules going to be implemented as expansion packs as discussed in https://github.com/facebookexperimental/rome/issues/173 ? It didn't seem like the discussion was conclusive. Maybe this is a good time to make that decision.

**Comment by sebmck** [comment]
Thinking about expansion packs, it feels like having an on switch just for the sake of it. We can detect the React code pretty unambiguously so there's no reason to have configuration to turn it on.

**Comment by tatchi** [comment]
Something that we might consider: https://twitter.com/dan_abramov/status/1255237989548134405?s=20

**Comment by macovedj** [comment]
Is it safe to assume that the recommended rules are not superfluous?  If there's not going to be an expansion pack, could people have at those ones?

**Comment by VictorHom** [comment]
If no one has started working on jsx-a11y/accessible-emoji, can I take a look at it?

**Comment by VictorHom** [comment]
if also available, can I work on `react/require-render-return`?

**Comment by VictorHom** [comment]
I'm going to take a look at implementing: `react/no-did-update-set-state` if no one has started 🙏

**Comment by sebmck** [comment]
Before submitting React or JSX lint rules of any kind please get confirmation in this issue or on the Discord.

**Comment by sebmck** [comment]
@jamiebuilds Could you look at finalizing the rule list? The comment at the top with a link in big bold letters looks like it's finalized and ready for people to work on. While a lot of them are fine, I don't want someone to spend a lot of time on ones that we don't want only to have their PR rejected.

**Comment by bitpshr** [comment]
Grabbing `jsx-a11y/no-autofocus`, `jsx-a11y/no-access-key`, and `jsx-a11y/scope`.

**Comment by bitpshr** [comment]
Grabbing `jsx-a11y/autocomplete-valid`, `jsx-a11y/heading-has-content`, and `jsx-a11y/no-distracting-elements`.

**Comment by VictorHom** [comment]
grabbing:
`react/no-will-update-set-state`,
`aria-unsupported-elements`
`anchor-has-content`

**Comment by ematipico** [comment]
I would like to work on `jsx-a11y/lang`

**Comment by VictorHom** [comment]
going to take a look at:
`no-autofocus`
`no-distracting-elements`
`no-access-key`
`media-has-caption`

**Comment by bitpshr** [comment]
@VictorHom just a heads up, `jsx-a11y/no-autofocus`, `jsx-a11y/no-distracting-elements`, and `jsx-a11y/no-access-key` should already be done.

**Comment by ematipico** [comment]
I'd like to tackle: 
- `jsx-a11y/mouse-events-have-key-events`
- `jsx-a11y/role-has-required-aria-props`

**Comment by KevinKelbie** [comment]
I'll have a go at `jsx-a11y/aria-props`

**Comment by VictorHom** [comment]
If possible, I want to take a look at `react-hooks/rules-of-hooks` unless someone else is working on it

**Comment by VictorHom** [comment]
Also, I would like to take a look at `jsx-no-useless-fragment`

**Comment by bitpshr** [comment]
Grabbing `import/no-anonymous-default-export`.

Has the spreadsheet above been fully triaged? Is the idea to implement all rules listed in that document, except for those marked in red as explicitly unnecessary? I'm personally in favor of a very opinionated set of lint rules as long as they can be silenced.

cc @sebmck

**Comment by sebmck** [comment]
@bitpshr 

> Grabbing `import/no-anonymous-default-export`.

We have the rule `defaultExportSameBasename` that enforces that the default export id of a module matches. Right now it just checks `id !== undefined` so we should modify that rule. We can also rename it since the name is weird.

> Has the spreadsheet above been fully triaged? Is the idea to implement all rules listed in that document, except for those marked in red as explicitly unnecessary? I'm personally in favor of a very opinionated set of lint rules as long as they can be silenced.

I think that document is up to date? I know @jamiebuilds was trying to find the time to finalize it. The ones in red we definitely don't want, same with general `createClass` rules. Class components are still fair game though. I'm also in favor of very opinionated rules, even if you need to suppress it in a limited set of circumstances.

We can also have rules not in that list. Maybe there are some rules that are easier to write in Rome that aren't in eslint, or that are easier to justify with Rome's better autofixes.

**Comment by jamiebuilds** [comment]
So here's a list of things we generally want to avoid:

- Rules specific to APIs that have been deprecated for awhile `React.createClass`/etc
- Rules where they are not useful (or not useful enough) without some additional configuration (Example: `react/forbid-component-props`)
- Rules for things that are/can be handled by the formatter in Rome (Example: `react/jsx-curly-newline`)
- Rules that enforce "silly" syntactic things, like sorting object properties, or forcing you to use one syntax over another without any concrete benefits (Example: `react/function-component-definition`)
- Rules that try to enforce something that they can't really enforce without things like a type-information or side-effect tracking. (Example: `react/no-access-state-in-setstate` doesn't enforce the thing its trying to enforce)
- Rules that aren't necessary in Rome (Example: `react/jsx-uses-react`)

If you have a question about a particular lint rule, please reach out and ask about it before you go and implement it

**Comment by ljharb** [comment]
Agree with that list, except that `function-component-definition` does have concrete benefits (whether you care about them or not) :-)

**Comment by bitpshr** [comment]
Currently working on:

- `react/button-has-type`
- `react/forbid-foreign-prop-types`
- `react/no-deprecated`
- `react/no-did-mount-set-state`
- `react/no-redundant-should-component-update`
- `react/no-unsafe`

**Comment by smlmrkhlms** [comment]
I will have an initial pass at `jsx-a11y/no-onchange` if it is unclaimed.

**Comment by VictorHom** [comment]
I am going to take on `jsx-fragments` since I am looking at `jsx-no-useless-fragment` as well if that's alright. 

A question I have is, in `jsx-fragments` do want to enforce one `<>...</>` over `<React.Fragment>...<React.Fragment> or <Fragment/>...</Fragment>`?

**Comment by sebmck** [comment]
@VictorHom I think we do. I can't imagine why you'd want `React.Fragment` instead of `<>`.

**Comment by jamiebuilds** [comment]
Does `<>` have a `key` syntax yet?

**Comment by ljharb** [comment]
That is indeed the primary reason why you *must* use `React.Fragment`; the other is if an API takes a "component", and the component you want to pass is React.Fragment.

**Comment by VictorHom** [comment]
Does it always have to be `<React.Fragment>`?

Would we maybe want to only support `<Fragment>` and `<>`? (I ask because of how the ast looks, but wanted to clarify)

**Comment by bitpshr** [comment]
I think that we should support both `<Fragment>` and `<React.Fragment>` for cases where a key is used. I feel that it's overly-opinionated to mandate destructured imports. For what it's worth, most other rules that check for members on the default React export check for both cases, e.g. `React.createElement` and `createElement`. If they don't, we'll probably have to do a pass to make sure this is uniformly handled.

**Comment by smlmrkhlms** [comment]
Would it be okay if I start working on `react/no-string-refs`?

**Comment by sebmck** [comment]
Go for it!

**Comment by smlmrkhlms** [comment]
I can start working on `react/no-is-mounted` if there are no objects.

**Comment by bitpshr** [comment]
@smlmrkhlms: I don't think we need to implement this rule since we're ignoring rules and logic paths within rules that only apply to `createReactClass`. Apologies, I'll try to get the document updated.

**Comment by VictorHom** [comment]
gonna take a look at `click-events-have-key-events` if no one is working on it

will follow up on `jsx-no-useless-fragment` after I address `jsx-fragments` (not that they are dependent)

**Comment by VictorHom** [comment]
going to also take a look at `anchor-is-valid` rule if no one is working on it.

**Comment by ematipico** [comment]
Working on: 
- `jsx-a11y/no-noninteractive-tabindex`
- `jsx-a11y/no-noninteractive-element-to-interactive-role`

**Comment by VictorHom** [comment]
I'll look at `no-access-state-in-setstate` if no one is working on that

**Comment by VictorHom** [comment]
I'll take a look at `react/no-array-index-key` if no one is working on it

**Comment by VictorHom** [comment]
I'll take a look at `jsx-pascal-case` if no one is working on it.

**Comment by yeonjuan** [comment]
I want to work on `react/jsx-no-literals`. :)

**Comment by VictorHom** [comment]
I would like to take a look at `react-hooks/rules-of-hooks` if no one is looking at that one

**Comment by UsamaHameed** [comment]
I would like to take a look at `react/default-props-match-prop-types` if no one else is already working on it.

**Comment by VictorHom** [comment]
There's been other things happening recently, but I am still working on these rules:
`no-this-in-sfc`
`react-hooks/rules-of-hooks`
`react/no-array-index-key`

**Comment by yeonjuan** [comment]
Can I take a `require-render-return`?

**Comment by Kelbie** [comment]
I'll take `autocomplete-valid`

**Comment by yeonjuan** [comment]
I'll take `react/no-render-return-value`.

**Comment by VictorHom** [comment]
gonna start on `react-hooks/rules-of-hooks`

I'll also take a look at `react/jsx-props-no-spreading`

**Comment by stefanuros** [comment]
Ill take a look at react/sort-comp

**Comment by VictorHom** [comment]
Still working on `react-hooks/rules-of-hooks`. I should have something soon

**Comment by aravind1078** [comment]
i will take `react/no-this-in-sfc` ?

**Comment by aravind1078** [comment]
can i try `react/state-in-constructor` ?

**Comment by sebmck** [comment]
Hey everyone! I'd like to pause development of new React lint rules (if you're currently working on or have reserved something in this thread then feel free to complete it!). We're preparing for our first release and should focus on stability and polish.

We need to take a more comprehensive look on the sort of React rules and patterns we want to encourage (ideally with approval from the React team or "community leaders" (whatever that means lol)). For that reason there may be some rules that will undergo significant tweaks or even removal. I'll make sure to keep this thread updated with those discussions and as we finalize any guidelines in case anyone wants to get involved.

Thank you everyone for your participation so far! Really exciting to see the contributions.

**Comment by sebmck** [comment]
Going to close this and use more finegrained issues.
