### ISSUE TITLE
📎 Add `version` command

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3410]
### Description

Allow users to query the version of Rome using the CLI. 

## `--version` Argument

Add a `--version` argument that prints the version of the CLI to stdout and exits. 

**Prior Art**:

```
❯ docker --version
Docker version 20.10.18, build b40c2f6b5d

❯ node --version
v16.14.2
```

## `version` Command

Add a `version` command that also prints the version of the Rome server if running (and may support additional arguments in the future).

**Prior Art**:

```
❯ docker version
Client:
 Version:           20.10.18
 API version:       1.41
 Go version:        go1.19.1
 Git commit:        b40c2f6b5d
 Built:             Sat Sep 10 11:31:10 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
Server:
  Version: 		... 

❯ git version --build-options
git version 2.38.0
cpu: x86_64
no commit associated with this build
sizeof-long: 8
sizeof-size_t: 8
shell-path: /bin/sh

❯ npm version
{
  'prettier-playground': '1.0.0',
  npm: '8.5.0',
  node: '16.14.2',
  v8: '9.4.146.24-node.20',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1n+quic',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
```

## Tasks

- [ ] Embed `version` in `rome` binary (`rome --version` must work even if not spawned with node).
- [ ] Add `--version` argument
- [ ] Add `version` command
