### ISSUE TITLE
☂️ Website improvements

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3447]
### Description

This is an umbrella issue to collect improvements to our current website. This covers changes to the content as well as fixing broken functionality. 

### Must

* [x] Rewrite Getting Started section #3547

### Improvements

* [ ] Go through linter/formatter documentation
* [x] Extend editor section (I like the [AstroBuild *Editor Setup* page](https://docs.astro.build/en/editor-setup/))
* [ ] Document ignoring files
* [ ] Document JSX suppression comments
* [ ] Migration Guide @sebmck 
* [ ] System requirements: Mention glibc requirements?
* [x] CLI redirects #3550 
* [x] Add package manager tabs @sebmck 

## Nice to have
* [ ] Troubleshooting section
* [ ] Document Helix editor

**Comment by ematipico** [comment]
I think we should expand the "Architecture" chapter, and maybe explain how the VSCode extension work with this new architecture (since it's a client)
