### ISSUE TITLE
☂️ Sort imports

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3462]
### Description

Today's editors have very good support for automatically adding imports but do so by adding them at the end of the import statements (or specifiers). 

The result is that it is often necessary to manually tune the imports to, e.g. group them by source.

## Goal

Add support for sorting imports and import specifiers to the formatter. Sorting imports should be opt-in because changing the ordering of import statements changes the order in which imported modules are executed, resulting in observable differences. 

## Tasks 

- [x] Add a new option to enable import sorting (disabled by default)
- [x] Sort (natural ordering) import specifiers (per import statement, not across import statements)
- [x] Sort (natural ordering) import statements by their module source. Treat an empty line or non-import statement as the start of a new import statement group and do the sorting per group. 
- [x] Add configuration support to automatically form groups depending on the module source.
- [x] CLI integration

## Prior work

#2512

## Inspiration

[prettier-plugin-sort-imports](https://github.com/trivago/prettier-plugin-sort-imports)

**Comment by MichaReiser** [comment]
@leops I remember we once discussed whether this is something that should be implemented in the formatter or as a lint rule due to its unsafe nature. Do you remember our conclusion?

**Comment by Conaclos** [comment]
IMO this should be a linting rule with auto fix. I never heard about import ordering at formatter level…

**Comment by ematipico** [comment]
> IMO this should be a linting rule with auto fix. I never heard about import ordering at formatter level…

There's a plugin for prettier, Micha attached a link to it and the end of the description :)

**Comment by MichaReiser** [comment]
> IMO this should be a linting rule with auto fix. I never heard about import ordering at formatter level…

Sorting imports is a tricky one and I can see reasons for it to be implemented in the formatter OR linter because I think it mainly comes down to how users prefer when imports are sorted:

* On save
* Only when manually applied

I don't see a reason why it shouldn't be possible to add support for code actions that are automatically applied when saving a file if the user explicitly opted in for that. 

The main reason why I would still implement the functionality as part of the formatter at least for now is that the formatter has superior comments support that ensures that no comments are dropped, which I see as essential for any functionality that automatically runs on save. 

We may decide in the future to move the logic from the formatter to the linter or simply decide to also offer a lint rule where the code fix calls into the formatter. 


Other prior art when it comes to sorting "imports" is

* Rustfmt sorts 'use' statements [PR](https://github.com/rust-lang/rustfmt/issues/4107)
* IntelliJ or Eclipse in Java [Stackoverflow](https://stackoverflow.com/questions/14716283/is-it-possible-for-intellij-to-organize-imports-the-same-way-as-in-eclipse)

**Comment by qweered** [comment]
This may be helpful https://github.com/lydell/eslint-plugin-simple-import-sort

**Comment by IanVS** [comment]
I maintain a fork of the prettier plugin mentioned above, which respects side-effect imports because it is unsafe to sort them.  https://www.npmjs.com/package/@ianvs/prettier-plugin-sort-imports

Having some kind of functionality to sort imports similar to that plugin is the biggest thing that will keep me from adopting rome.  Otherwise, the speed is amazing and I'd jump on it in a heartbeat.

**Comment by jeysal** [comment]
This might be a bit far into the future, but a lint rule could evolve to do cool stuff like

1. Check `package.json` for `sideEffects: false`
2. If it's set, offer reordering as a safe fix. Else, offer reordering and writing `sideEffects: false` into package.json as a suggested fix with a good diagnostic explaining the implication.

or something along those lines.

Whether `sideEffects` is even a good convention that Rome would want to support, is of course a different question.
But either way, this seems to me like something that extends far beyond the formatter. I also think there's a whole class of features hidden behind this, such as linting side-effect imports or obviously side-effect-full statements in code declared to be side-effect free.

I would thus argue against constraining Rome in how these things will be handled in the future by putting something like this into the formatter, which is supposed to operate on a plain AST input and a few config options with no further project context.

**Comment by sebmck** [comment]
Let's figure out a way to prioritize this.

**Comment by lcswillems** [comment]
Thanks to this issue and the comment of @IanVS, I have discovered his plugin:

https://github.com/ianvs/prettier-plugin-sort-imports

His plugin doesn't sort imports with side effects and add great features such as `importOrderMergeDuplicateImports`. Great work Ian!

I hope one day this will be built-in in Rome to not have to install an additional plugin and enjoy fast formatting / linting. For the moment I am staying with Prettier.

**Comment by lcswillems** [comment]
@leops I see that [PR](https://github.com/rome/tools/pull/3818) closed this issue. Does the PR implement the last checkbox of the issue, i.e. "Add configuration support to automatically form groups depending on the module source."?

If not, do you want me to open another issue for this particular point? This is the remaining point preventing me to use Rome.

**Comment by leops** [comment]
Sorry I forgot I had tagged this issue in the PR, it got erroneously closed since #3818 only implements the baseline feature, but it's still missing many crucial features (and in particular everything related to configuration)

**Comment by lcswillems** [comment]
Hi @MichaReiser ,

What do you mean by "Add configuration support to automatically form groups depending on the module source."? Do you mean grouping with regex such that [prettier-plugin-sort-imports](https://github.com/trivago/prettier-plugin-sort-imports) allows to do?

**Comment by lcswillems** [comment]
In my case, I use the [prettier-plugin-sort-imports](https://github.com/ianvs/prettier-plugin-sort-imports) pluging of ianvs.

And this configuration in my `package.json`:

```
"prettier": {
  "importOrder": [
    "^~(.*)$",
    "^\\$(.*)$",
    "^[./]"
  ],
  "importOrderBuiltinModulesToTop": true,
  "importOrderMergeDuplicateImports": true,
  "importOrderCombineTypeAndValueImports": true
},
```

**Comment by hyoretsu** [comment]
Imo this is also an implementation to consider

https://github.com/Tibfib/eslint-plugin-import-helpers

**Comment by Aaronkala** [comment]
This is a popular `eslint` version https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md. We have eslint fix all setup to run on save after prettier.

**Comment by ematipico** [comment]
This feature will be shipped in the next release: `v12.0.0`

**Comment by lcswillems** [comment]
@ematipico Has the point "Add configuration support to automatically form groups depending on the module source." been added? I don't see configuration to group imports.
