### ISSUE TITLE
☂️ v10 release

### ISSUE THREAD

**Issue by sebmck** [rome/tools#3575]
# Before Release Day

## Benchmark

- [x] Merge `benchmark` branch
- [x] Use M1 Macbook performance numbers in all public benchmark results
- [x] Ensure `benchmark` folder has a `README` with instructions to reproduce

## `rome.tools`

- [x] Update blog cover photo
- [x] Setup Google analytics

## `docs.rome.tools`

- [x] Remove docs "back chevron" in favor of a navigation dropdown
- [x] Finish editor documentation
- [x] Setup Google analytics

# On Release Day

- [x] Publish new blog post to `rome.tools`
- [x] Merge release branch #3526 

## Publicize

- [x] Tweet from `@sebmck` and retweet from `@rometools`: https://twitter.com/sebmck/status/1589987087780302848
- [x] Post to Reddit: https://www.reddit.com/r/javascript/comments/ypnwwn/announcing_rome_v10_first_stable_release_of_our/
- [x] Post to HN: https://news.ycombinator.com/item?id=33519318

**Comment by Boshen** [comment]
> npm instal rome
> added 5 packages

This doesn't look right, it should be only 1 package.

Test:
```
~/github/rome ❯ npm install rome --no-audit

added 1 package in 2s

~/github/rome ❯ ls -a node_modules/
.                  ..                 .bin               .package-lock.json rome
```

**Comment by Boshen** [comment]
```
~/github/rome ❯ ls node_modules/@rometools/
cli-darwin-x64 wasm-bundler   wasm-nodejs    wasm-web
```

I see, we now have these guys.

**Comment by MichaReiser** [comment]
> > npm instal rome
> 
> > added 5 packages
> 
> 
> 
> This doesn't look right, it should be only 1 package.
> 
> 
> 
> Test:
> 
> ```
> 
> ~/github/rome ❯ npm install rome --no-audit
> 
> 
> 
> added 1 package in 2s
> 
> 
> 
> ~/github/rome ❯ ls -a node_modules/
> 
> .                  ..                 .bin               .package-lock.json rome
> 
> ```

Hmm, I thought that was fixed. Let me have a look at it

**Comment by MichaReiser** [comment]
Verified: this if fixed in the latest nightly version

```
❯ npm install rome@nightly

added 2 packages, and audited 4 packages in 664ms
```

There are two packages: One is the node wrapper, and the other is the native binary for the platform
