### ISSUE TITLE
☂️ Linter 11.0.0

### ISSUE THREAD

**Issue by ematipico** [rome/tools#3739]
# Description

Issue to track works around the linter to this release cycle

## Infra

- [x] https://github.com/rome/tools/pull/3542

## Rules
- [x] https://github.com/rome/tools/issues/3640 
- [ ]  Support of ARIA roles to existing accessibility rules (task under review, this is probably not needed once all a11y rules will fall into pieces) 
- [ ] #3888
- [ ] #3889
- [ ] https://github.com/rome/tools/issues/3850
- From `eslint`
    - [ ] #3481
    - [x] [`noUnsafeFinally`](https://eslint.org/docs/latest/rules/no-unsafe-finally)
    - [ ] [`noDuplicateCase`](https://eslint.org/docs/latest/rules/no-duplicate-case)
- From `clippy`
    - [x] #3368
    - [ ] [`useCollapsibleIf`](https://rust-lang.github.io/rust-clippy/master/#collapsible_if)
    - [ ] [`noRedundantClosure`](https://rust-lang.github.io/rust-clippy/master/#redundant_closure)

### Accessibility

- [x] #3813
- [x] #3814
- [x] #3815
- [x] #3816
- [x] #3817
- [x] #3822
- [x] #3886
- [x] #3887

### React hooks rules

More details about

 https://github.com/rome/tools/pull/3355
Checks the dependencies array of React Hooks contains all referenced bindings
Example error:
function Component({ prop }) { useEffect(() => { prop(); }, []); }

 - [x] Missing dependencies;
 - [x]  Extra dependencies;
 - [x]  Consider some React hooks returns as stable;
 - [x] Consider const a = <some constant>; see https://github.com/rome/tools/pull/3508
 - [ ] Consider declarations inside the React component that are potentially capturing non-stable variables.
 - [ ] Incorporate eslint tests
 - [x] improved configuration https://github.com/rome/tools/pull/3542
 - [x] Correctly suggest dependencies for properties: "a.b" and "a.c" instead of "a" https://github.com/rome/tools/pull/3581
 - [ ] Correctly deal with globals and undefined dependencies
