### ISSUE TITLE
☂️ Linter, port eslint's recommended preset 

### ISSUE THREAD

**Issue by ematipico** [rome/tools#3953]
### Description

# WORK IN PROGRESS, NOT YET READY, PLEASE DON'T IMPLEMENT ANY YET

This umbrella is meant to track all the rules that belong to the recommnded preset of ESLint, and move them to Rome. 

Some rules already exists and they might have a different name. 

[This spreadsheet] tracks all of them, with the relative rule in Rome.

The community might decide to split some rule into multiple rules, for different reasons:
- technical constraints (use different query systems in one rule is not possible in Rome);
- break down the scope of a rule into more specialized rules (for example in https://github.com/rome/tools/issues/3731 there was a discussion that ended up splitting a rule in multiple rules);
- our grouping system might not fit for a rule;

## Contribution guidelines

Always refer to our [contribution guidelines](https://rustdocs.rome.tools/rome_analyze/index.html#analyzer) when implementing rule. 

When porting a rule, make sure that the name of the rule reflects our internal naming patterns, and refrain from using abbreviations in the name of the rule. We try to promote complete names whenever it's possible.

## List of rules

Below, is the list of recommended rules that *haven't been* implemented yet.

- [ ] [https://eslint.org/docs/latest/rules/no-class-assign](https://eslint.org/docs/latest/rules/no-class-assign)
- [ ] [https://eslint.org/docs/latest/rules/no-constant-condition](https://eslint.org/docs/latest/rules/no-constant-condition)
- [ ] [https://eslint.org/docs/latest/rules/no-control-regex](https://eslint.org/docs/latest/rules/no-control-regex)
- [ ] [https://eslint.org/docs/latest/rules/no-dupe-class-members](https://eslint.org/docs/latest/rules/no-dupe-class-members)
- [ ] [https://eslint.org/docs/latest/rules/no-dupe-else-if](https://eslint.org/docs/latest/rules/no-dupe-else-if)
- [ ] [https://eslint.org/docs/latest/rules/no-duplicate-case](https://eslint.org/docs/latest/rules/no-duplicate-case)
- [ ] [https://eslint.org/docs/latest/rules/no-empty-character-class](https://eslint.org/docs/latest/rules/no-empty-character-class) (note: the name to me is misleading)
- [ ] [https://eslint.org/docs/latest/rules/no-fallthrough](https://eslint.org/docs/latest/rules/no-fallthrough)
- [ ] [https://eslint.org/docs/latest/rules/no-inner-declarations](https://eslint.org/docs/latest/rules/no-inner-declarations)
- [ ] [https://eslint.org/docs/latest/rules/no-irregular-whitespace](https://eslint.org/docs/latest/rules/no-irregular-whitespace)
- [ ] [https://eslint.org/docs/latest/rules/no-misleading-character-class](https://eslint.org/docs/latest/rules/no-misleading-character-class)
- [ ] [https://eslint.org/docs/latest/rules/no-obj-calls](https://eslint.org/docs/latest/rules/no-obj-calls)
- [ ] [https://eslint.org/docs/latest/rules/no-prototype-builtins](https://eslint.org/docs/latest/rules/no-prototype-builtins) although instead of promoting `hasOwnProperty`, we should promote `hasOwn`, which is supposed to be the native replacement
- [ ] [https://eslint.org/docs/latest/rules/no-self-assign](https://eslint.org/docs/latest/rules/no-self-assign)
- [ ] [https://eslint.org/docs/latest/rules/no-self-compare](https://eslint.org/docs/latest/rules/no-self-compare)
- [ ] [https://eslint.org/docs/latest/rules/no-this-before-super](https://eslint.org/docs/latest/rules/no-this-before-super)
- [ ] [https://eslint.org/docs/latest/rules/no-unexpected-multiline](https://eslint.org/docs/latest/rules/no-unexpected-multiline) (this is used to protect people from ASI, but our formatter does that already, should we recommend this by default? I would personally not, to promote the usage of both formatter and linter)
- [ ] [https://eslint.org/docs/latest/rules/no-unsafe-optional-chaining](https://eslint.org/docs/latest/rules/no-unsafe-optional-chaining)
- [ ] [https://eslint.org/docs/latest/rules/no-useless-backreference](https://eslint.org/docs/latest/rules/no-useless-backreference) (regex… might be though for us)
- [ ] [https://eslint.org/docs/latest/rules/use-isnan](https://eslint.org/docs/latest/rules/use-isnan)
- [ ] [https://eslint.org/docs/latest/rules/no-extra-semi](https://eslint.org/docs/latest/rules/no-extra-semi) (we already have the formatter, I would personally not implement it, to promote the usage of both formatter and linter)
- [ ] [https://eslint.org/docs/latest/rules/no-nonoctal-decimal-escape](https://eslint.org/docs/latest/rules/no-nonoctal-decimal-escape)
- [ ] [https://eslint.org/docs/latest/rules/no-redeclare](https://eslint.org/docs/latest/rules/no-redeclare)
- [ ] [https://eslint.org/docs/latest/rules/no-unused-labels](https://eslint.org/docs/latest/rules/no-unused-labels)
- [ ] [https://eslint.org/docs/latest/rules/no-useless-escape](https://eslint.org/docs/latest/rules/no-useless-escape) (regex, warning!)
- [ ] [https://eslint.org/docs/latest/rules/no-with](https://eslint.org/docs/latest/rules/no-with)
- [ ] [https://eslint.org/docs/latest/rules/require-yield](https://eslint.org/docs/latest/rules/require-yield)

**Comment by mzbac** [comment]
Is it possible to categorise the rule into different difficulty groups? Some people would know how to pick it up based on their level.

**Comment by ematipico** [comment]
> Is it possible to categorize the rule into different difficulty groups? So people would know how to pick it up based on their level. I am pretty new to Rome and Rust, so I had a lot of trouble picking the right issue to contribute.

Yes, that's what I plan to do with each rule, I started doing so with the Accessibility rules.
