### ISSUE TITLE
☂️ Parse `rome.json` using the rome JSON parser

### ISSUE THREAD

**Issue by ematipico** [rome/tools#4042]
### Description

At the moment our `Configuration` object is deserialized from a JSON string using `serde`. This, while working fine so far, has some limitations to our infrastructure:
- we rely on the parsing infrastructure of `serde`, which is not error-tolerant;
- we rely on the error messages emitted by `serde`, which have some limitations when we want to emit diagnostics; 
- we can't provide good diagnostics (with suggestions, for example) when encountering an error;

`Configuration`, eventually, would become useless and we could potentially become obsolete, and work straight for the `WorkspaceSettings`, although `Configuration` still needs to exist for the following reasons:
- we emit a JSON schema straight from `Configuration`, which needs to implement `serde`;
- in the future, we would need to **serialize** soma data to the `rome.json` file; an example is via CLI, with commands like `rome config enable formatter`, which will modify in place the `rome.json` file;

This umbrella will track tasks to implement the parsing and deserialization of the `rome.json` file:
- [x] implement a generic infrastructure to visit the configuration
- [x] implement a specialized infrastructure to visit the JSON configuration 
- [x] visit, parse and validate the `rome.json` type
- [x] visit, parse and validate the `rome.json#files` type
- [x] visit, parse and validate the `rome.json#formatter` type
- [x] visit, parse and validate the `rome.json#linter` type
- [x] visit, parse and validate the `rome.json#javascript` type
