### ISSUE TITLE
☂️ Move Rome CLI to use `bpaf`

### ISSUE THREAD

**Issue by ematipico** [rome/tools#4397]
### Description

I have been experimenting with some possible CLI libraries (more potent than `pico_args`), and I find [`bpaf`](https://github.com/pacak/bpaf) really pleasant to work with!

I did a small PoC and it seems that it can work inside the Rome code base, although there are some restrictions and compromises that we have to make:
- we can't use our internal `markup!` for the help section;
- error handling will be different, and we have to rely on `bpaf` error messages when the parsing of an argument fails;

I am happy to accept the trade-off! `bpaf` allows to define arguments in two ways: combinatoric or `derive`. For Rome, the `derive` feature works better. The combinatoric way forces you to define every type inside a struct, which differs from what we're looking for inside Rome.

Although, before moving everything to `bpaf`, some more work needs to be done to lay off the foundations and make the migration smoother.

Below the list of things that we need to do:

First batch:
- [x] #4398
- [x] #4399
- [x] #4400

Second batch:
- [x] Move global options to their own struct
- [x] `format` subcommand via `bpaf`
- [x] `check` subcommand via `bpaf`
- [x] `ci` subcommand via `bpaf`
- [x] `rage` subcommand via `bpaf`

**Comment by Conaclos** [comment]
Which other candidates did you review?

**Comment by ematipico** [comment]
> Which other candidates did you review?

Another option is `clap` but it's super heavy and I'd prefer to avoid it.


Another one was `argh` but it has less features.

Here's a great community project that compares some libraries: https://github.com/rosetta-rs/argparse-rosetta-rs

I like `bpaf` because:
- it has multiple styles for composing the parsing of arguments
- it has third party auto completion in case we want to opt-in
- it's actively maintained

**Comment by Boshen** [comment]
I agree with your conclusion on `clap` and `argh`. Can't wait to see `bpaf` getting used. Maybe I'll convert it in Oxc before Rome does, if I get the time 😁

**Comment by pacak** [comment]
> we can't use our internal markup! for the help section;

Can you tell me a bit more what makes `markup!` macro great or where can I read about it? I'm looking into changing help/documentation generation so might be able to make it more compatible...

**Comment by ematipico** [comment]
> > we can't use our internal markup! for the help section;
> 
> Can you tell me a bit more what makes `markup!` macro great or where can I read about it? I'm looking into changing help/documentation generation so might be able to make it more compatible...

Hi @pacak , thank you for reaching out! :)

The `markup!` macro is an internal macro that accepts a string HTML-like:

```rs
markup!{
	"Something"<Emphasis>"bold"</Emphasis>" or "<Dim>"dimmed"</Dim>
}
```

This macro creates `MarkupElements` with an internal implementation of `rome_console::fmt::Display`. Then, we have different writers based on where we want to write this elements. We have a Terminal writer and an HTML writer.

Here's some internal, useful links:
- The formatter implementation: https://github.com/rome/tools/blob/main/crates/rome_console/src/fmt.rs
- The terminal writer: https://github.com/rome/tools/blob/main/crates/rome_console/src/write/termcolor.rs
- The HTML writer: https://github.com/rome/tools/blob/main/crates/rome_console/src/write/html.rs
- The definition of the markup elements: https://github.com/rome/tools/blob/main/crates/rome_console/src/markup.rs

**Comment by pacak** [comment]
I see. I'm adding something similar with goals to write to terminal, markdown (well, technically a mix of html and markdown) and manpages, there should be a way to get those two to talk to each other :)
