### ISSUE TITLE
☂️ Create `rome_json_analyze` crate

### ISSUE THREAD

**Issue by ematipico** [rome/tools#4444]
### Description

Now that Rome "knows" JSON files, we should be able to create rules to lint JSON files. 

The new crate should be similar to what we have inside `rome_json_analyze`.

A rule that we could create for this new crate could be `suspicious/noDoubleKeys` (name subject to change), which should check for the presence 
of double keys inside a JSON file:
```json
{
	"foo": "bar",
	"foo": "baz"
}
```

Here's a list of tasks (not in order, maybe something is missing):

- [x] create a new `rome_json_analyze` crate
- [x] create a test suite inside `rome_json_analyze`
- [x] wire the new crate with the workspace (`file_handlers/json.rs`)
- [x] update `generate_configuration.rs` to auto-generate the configuration and add these new rules
- [x] update `lintdoc` to emit and "check" the documentation of the rules inside `rome_json_analyze`
- [x] create `suspicious/noDoubleKeys`

@rome/core-contributors are you interested in implementing the feature? I am very interested in this, because it would allow us to create excellent rules.

For example, I am currently working on plugging the `package.json` into rome, and we could have rules that emit diagnostics/warnings. For example, I am thinking of creating a rule that checks the licenses, and it will emit an error/warning.
