### ISSUE TITLE
☂️ Enable method parameters decorators via option

### ISSUE THREAD

**Issue by ematipico** [rome/tools#4562]
### Description

Previous issue: https://github.com/rome/tools/issues/4540

We want to support method parameters decorators, but only under a flag that explains to the user that doing so is not safe because it's a legacy language proposal that never reached Stage 4. Instead, a new one was created. 

Ideally, we should create an opt-in option:

```json
{
	"javascript": {
		"parser": {
			"unsafeParameterDecoratorsEnabled": true
		}
	}
}
```

And we can document that `unsafe*` options are for features that are not standard and should be used carefully (bugs and stuff).

- [x] #4573
- [x] #4586
- [x] #4595
- [x] https://github.com/rome/tools/issues/4631
- [x] https://github.com/rome/tools/issues/4608
- [x] https://github.com/rome/tools/issues/4606
- [x] #4729

**Comment by denbezrukov** [comment]
I've started to investigate the issue.
I'm unsure about the optimal approach to designing decorators in the parameter list.

For example:
https://github.com/rome/tools/blob/b3340e4c25aaf276dd6ac3f1d7560fab4799961f/xtask/codegen/js.ungram#L684-L689
https://github.com/rome/tools/blob/b3340e4c25aaf276dd6ac3f1d7560fab4799961f/xtask/codegen/js.ungram#L1580-L1589

We can't do something like this:
```
AnyJsConstructorParameter =
        decorators: JsDecoratorList <--- it's not ok
	AnyJsFormalParameter
	| JsRestParameter
	| TsPropertyParameter

```

We have several options:
1.  Wrap `AnyJsParameter` and `AnyJsConstructorParameter` into a different node.
```
AnyJsDecoratedParameter = 
 decorators: JsDecoratorList
 parameter: AnyJsParameter
```
2. Wrap each variant individually:
```
AnyJsDecoratedFormalParameter = 
 decorators: JsDecoratorList
 parameter: AnyJsFormalParameter
```
3.  Expand JsFormalParameter, JsRestParameter, TsPropertyParameter, TsThisParameter with a decorator node:

```
JsFormalParameter =
        decorators: JsDecoratorList
	binding: AnyJsBindingPattern
	'?'?
	type_annotation: TsTypeAnnotation?
	initializer: JsInitializerClause?
```
```
JsRestParameter =
        decorators: JsDecoratorList
	'...'
	binding: AnyJsBindingPattern
	type_annotation: TsTypeAnnotation?
```

Personally, I'm inclined to expand it because this approach doesn't disrupt the current formatter/linter logic. However, we'll need to ensure that decorators are not used outside of class member functions.

What do you think @rome/core-contributors ?

**Comment by ematipico** [comment]
@denbezrukov thank you for looking for a possible solution. I believe this is our best solution without disrupting our existing CST too much.

It's a pity that the typescript modifiers were put after the decorators; this disrupts everything. Although, given the circumstances, I believe your solution is perfect for us!
